### ISSUE TITLE
3.2 Imports show an empty tree in latest build

### ISSUE THREAD

**Issue by TheRealRequnix** [Openarl/PathOfBuilding#1006]
Not sure if this is intentional, but importing 3.2 builds (for example https://pastebin.com/0UZe8BEJ) results in an empty tree.

**Comment by Openarl** [comment]
The changes to the Shadow starting area mean that many Shadow builds will end up with a complete tree wipe; unfortunately there isn't anything I can do about this.

**Comment by zenunomacedo** [comment]
Would it be possible to enable selecting 3.2 or 3.3 in Game Version in the Configuration tab, which would change the passive skill tree and allow us to recover the 3.2 trees?

**Comment by Openarl** [comment]
Setting up a new game version is actually a major pain for various reasons, as the current design involves duplicating and maintaining a separate copy of all of the data files. I'd have to rework the game version system to avoid all that work; otherwise it isn't worth the effort.

However, I am looking into making some sort of migration script that will preserve most of the Shadow tree; it should be possible as the nodes that caused the reset were simply replaced with others, so I may just be able to do a 1:1 mapping.

**Comment by zenunomacedo** [comment]
Aight, thanks for the quick response :) I should be able to grab an older version of PoB to see the tree I'm concerned about, so it should not be a problem for me, but yea, a way to migrate it would be cooler.
