### ISSUE TITLE
[BUG] Missing some dps and can't figure why (v 1.0.19)

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#11]
So, I've copied my currently existing character and wanted to do some experiments with its gear/passives.
But it looks that I'm missing 71,38 dps unbuffed (I mean, totally unbuffed in town) for some reason. As I can see - it's not just some element/phys/chaos damage missing, but total mofidier lose somewhere.
![PoB DPS](http://i.imgur.com/wXUnrAL.png)
![Ingame](http://i.imgur.com/fgVWJbd.png)
Here's my saved profile for it [2.3 Champion Poison LA+Frostwall.zip](https://github.com/Openarl/PathOfBuilding/files/451400/2.3.Champion.Poison.LA.Frostwall.zip)

Also, worth to mention, that "Inspirational" from champion doesn't count at all. So in h/o I'm missing almost 2k dps.

**Comment by Openarl** [comment]
Ok, as far as I can tell the differences are down to two things:
1) As you mentioned, Inspirational isn't working; like a lot of ascendancy notables I simply hadn't had the time to add support for it. But since you asked, it's now supported as of the latest update, which should be out in the next hour.
2) The displayed DPS in Unbuffed mode does (somewhat confusingly) account for things like auras and other permanent effects. In this cause it also accounts for the "X while you have Fortify" effects since as Champion you have fortify active all the time... except when in town! If you go into your hideout the DPS numbers should be much closer (once you get the fix for Inspirational, that is).
Note that even then, the damage numbers aren't likely to match EXACTLY, there will be a small margin of error of 1% or so due to differences in rounding.

**Comment by dein0s** [comment]
Thanks for the p1.
And about second one - fortify doesn't affect my damage anyway as it's "melee" only and I was building a bow character with LA.

If you assume that that's because of math and rounding, then I'm fine with it.

**Comment by Openarl** [comment]
It doesn't affect your hit damage, but the attack speed from Unstoppable Hero is global, so it will apply.

**Comment by dein0s** [comment]
Oh, I see.
