### ISSUE TITLE
Ignite DPS and crits

### ISSUE THREAD

**Issue by kelthalas** [Openarl/PathOfBuilding#113]
Hello,

Currently path of building calculate the ignite DPS using (average non crit damage * crit effect modifier) which averages out the damage based on your crit chance. However this is not how crit based ignite builds work as you don't ignite when you don't crit, which means that your ignite DPS should always based on your (average non crit damage * crit MULTI).

For now I work around this by creating a fake item which puts me at 95% crit. But it would be nice to find a way to display this information easily

Thanks !

**Comment by Openarl** [comment]
Basing the ignite DPS on crits will only be accurate in the exact case where you have 0 ignite chance from other sources. In any case where both crit and non-crit ignites are possible, calculating your true ignite DPS becomes almost impossible without combat simulation. In fact, strictly speaking it's not completely accurate in other cases, due to variance in the damage of each hit... but I digress. 

In lieu of any accurate way of calculating the ignite DPS under all conditions, I could add options to the Configuration tab to control how ignite is calculated; at minimum the ability to choose between crit ignites and average damage ignites. Would that suit you?

**Comment by kelthalas** [comment]
That does sound like a reasonable option thanks

**Comment by Openarl** [comment]
Ok. I've got it working, so it'll be in the next update.
