### ISSUE TITLE
Damage with Ailments -> DOT

### ISSUE THREAD

**Issue by durrrrnado** [Openarl/PathOfBuilding#1202]
In 3.4 patch GGG changed nodes with "#% increased damage with Ailments" to "#% increased damage over time" in Ranger section at least.
So currently elemental dps is calculated incorrectly due to passive tree still contains Ailments increases not the DoT.

**Comment by Openarl** [comment]
That change only applied to Bow nodes, all of which are correctly shown with Damage over Time modifiers in PoB. It shouldn't even be possible for the program to show incorrect descriptions on passive nodes anyway, since that information is exported from the game's data files. If, however, you can identify a specific node that appears differently in the program than in-game, then please let me know.
