### ISSUE TITLE
better way to show overcapped res

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#122]
Would be nice if it showed total res like maybe in brackets on the left sidebar like 75% (169% total) (or maybe like in-game) or something, because you usually want to cap ele weakness and this tool now just makes it even more complicated and needs more maths, also not very practical under Calcs neither.

edit: also the rare cobal jewels are missing the resistances rolls to chose from, looks like only damage mods added so far.

**Comment by dein0s** [comment]
For elemental weakness you need 34 res over max, ain't that hard to remember and you don't need any "more math" except simple subtraction.
About jewels - only essential modifiers are included. You can always add rest manually. Check https://github.com/Openarl/PathOfBuilding/issues/88 for more info.

**Comment by Openarl** [comment]
I think showing the amount over cap is clearer than showing your total resistance, since with the overcap amount the only number you ever need to compare it with is 34, whereas the magic "169" only applies if you don't have increases to your maximum resistances. The total is always available in the Calcs tab if you really need it.
