### ISSUE TITLE
Some Flesh Offering buffs not recognized

### ISSUE THREAD

**Issue by HeyGitSome** [Openarl/PathOfBuilding#1225]
https://pastebin.com/ia9nn0MY

Enabling Flesh Offering's attack speed does not appear to be recognized as a buff for the Herald of Agony minion.

One place this is apparent is in the player's attack speed which can be modified by changes in minion attack speed, via the Spiritual Aid (or Spiritual Command) passive tree nodes.  Enabling Flesh Offering should change the player's attack speed (but doesn't) in the same way that happens with jewels and passive trees nodes that increase minion attack speed.

**Comment by Openarl** [comment]
Your understanding of this interaction is incorrect; Flesh Offering + Spiritual Command does **not** cause the player to gain Attack Speed, as the Flesh Offering buff is applied directly to your minions, rather than adding "Minions have xxxxx"-type stats to the player (which is what Spiritual Command/Aid apply to).
