### ISSUE TITLE
Rise of the Phoenix Low life attributes have no effect

### ISSUE THREAD

**Issue by GameXLife** [Openarl/PathOfBuilding#1245]
I reserve 66% of life, but it doesn't increase 25% fire resistance to my stat.
Even I check the "Are you always on Low Life", they still not worked.

**Comment by Openarl** [comment]
It's actually the Fire Resistance one specifically that's broken; it looks like it's had the wrong wording for a while ("25% increased Fire Resistance" rather than "+25% to Fire Resistance"), which prevents the program from recognising it correctly. 

I've fixed the wording in the Unique item database in the next update; you'll need to re-add it from there after the update to get the correct version; or you can edit the item yourself.
