### ISSUE TITLE
[BUG] Some unique affixes doesn't import correctly

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#13]
Some of unique affixes doesn't import when trying to copy-paste from game. 
And some templates also doesn't have this affixes (like [The Bringer of Rain Nightmare Bascinet](http://pathofexile.gamepedia.com/The_Bringer_of_Rain))
What I've found for now:
- Socketed Gems are Supported by %gem%
- Enemies you Attack Reflect %damage%
![Copy-pasted Marohi](http://i.imgur.com/6dd8nme.png)
![Template Marohi](http://i.imgur.com/Bzx4btZ.png)
![Copy-pasted Hiltless](http://i.imgur.com/HbnP6Sd.png)
![Template Hiltless](http://i.imgur.com/3ky8LaB.png)
![Copy-pasted BoR](http://i.imgur.com/D4ubxnQ.png)

**Comment by dein0s** [comment]
Not a big deal as 'Socketed Gems are Supported by %gem%' not implemented yet, but still.

**Comment by Openarl** [comment]
I'm aware that there are still a lot of item affixes that aren't supported. The thing is, there is a HECK of a lot of them and many of them require special support, so I haven't yet had time to implement them all. Truthfully I'll probably never get all of them working; same goes for passive skills (particularly Ascendancy notables). I've mostly just been implementing them as people request them; Socketed Gems are Supported by X is a major one I've been looking into, but it's a tricky one to do. For now you can just add the support manually.

**Comment by dein0s** [comment]
Yeah, I'm adding them manually right now.
But the thing is that if even they are exists in your templates (like with Marohi), they does not import correctly.
It may affect other imports also. Above are just an examples that I've found so far.

**Comment by Openarl** [comment]
Even though affixes like the Inc AoE support on Marohi aren't supported yet, they are still included in the items so that when I do add support they'll start working right away. I indicate which affixes are supported by showing them in blue, unsupported ones are white, so technically everything is working as designed.

**Comment by dein0s** [comment]
Looks like you don't get my point or i can't explain it properly :D (And I guess that's about me, because english is not my native.)

Just try to paste the below item stats (for Marohi) into PoB and you'll see that there's no 'Supported by X' on imported (pasted) item.
That's I was talking about.

```
Rarity: Unique
Marohi Erqi
Karui Maul
--------
Two Handed Mace
Quality: +20% (augmented)
Physical Damage: 324-502 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 0.99 (augmented)
--------
Requirements:
Level: 68
Str: 182
Int: 99
--------
Sockets: R-R-B-R-R 
--------
Item Level: 69
--------
20% increased Stun Duration on Enemies
--------
Socketed Gems are Supported by level 15 Increased Area of Effect
244% increased Physical Damage
Adds 10-20 Physical Damage
10% reduced Attack Speed
-100 to Accuracy Rating
10% reduced Movement Speed
45% increased Stun Duration on Enemies
--------
Lumbering as a sea lion, clumsy as a berry-drunk pigeon. That was Erqi. 
It mattered little. When Erqi's maul fell true, so did its target.
```

**Comment by Openarl** [comment]
Yeah, that's a tricky one to fix because the item text given by the client doesn't say what each section is for (doesn't say what part is the implicits or what part is explicits etc) so my program has to make educated guesses. It usually works, but if the explicits section starts with an affix that isn't supported/detected then it won't show. The good news is even though it won't show, the program will still remember it, and it'll show up as soon as I add support for it.

**Comment by Openarl** [comment]
The program now supports "Socketed Gems are Supported by" modifiers, which were the main cause of this issue, so I'll mark this as closed.
