### ISSUE TITLE
poet's pen - Error in the level of secketed gem calculation

### ISSUE THREAD

**Issue by plishty** [Openarl/PathOfBuilding#1324]
Hi,
the calculated ___level of the socketed gem is doubled___ : 
**having a +6 when it should be +3**
I've tried playing around with the affix to change the "*per X Player Levels*" value and it jump from +2 to +4 and then to +6 when it should be doing +1, +2 and +3.

**Comment by dobrowolsk** [comment]
Can confirm.
- editing the pen to have 0.5 per 25 levels doesn't work.
- editing the pen to have 1 per 50 levels doesn't work, because it isn't precise enough at the relevant level of 85-95.
- viable workaround is removing the mod altogether and manually changing the gem level.
- viable workaround is removing the mod altogether and adding an appropriate leveled Empower

The added physical damage per player level stat works correctly.

**Comment by plishty** [comment]
Fixed in version 1.4.122 (2019/01/01 happy new year)
closed / can marked as fixed
