### ISSUE TITLE
Window can be "lost" in unseen space

### ISSUE THREAD

**Issue by vegeto079** [Openarl/PathOfBuilding#138]
Hard to explain.. but basically the scenario:

- Have multiple monitors
- Place program onto separate monitor
- Turn off PC
- Turn on PC with only with the monitor that did not have program on it
- Turn on program
- It is seemingly now still in the space that the second monitor was, with no way of moving it (windows key+arrows does not move it when highlighted)

**Comment by Openarl** [comment]
Ok, so since next update will be updating the runtime (which handles window positioning, amongst other things), it's given me an opportunity to work on this. I've found a likely fix; the program now forces itself onto the nearest monitor if it finds itself offscreen when it starts. Let me know if the issue persists after the next update (1.2.36).

**Comment by Openarl** [comment]
I guess this is fixed, then.
