### ISSUE TITLE
Poison Duration calculation is incorrect

### ISSUE THREAD

**Issue by reportissue** [Openarl/PathOfBuilding#139]
![poisonduration](https://cloud.githubusercontent.com/assets/24785549/21955628/0d02c55e-daaa-11e6-9a86-413630d13083.jpg)

2*1.5 != 3.4

**Comment by Openarl** [comment]
Ok, I've had a quick look at this, and I think I know the cause. I'm guessing that this build is a Pathfinder, because the difference is exactly 20% increased duration, and the increased poison duration from Master Herbalist accounts for that. If that's the cause, then the issue is just with the breakdown display; the actual duration calculation is correct. Specifically, the duration modifier being shown there is the general modifier, not the modifier for poison. I've fixed that for the next update.

**Comment by reportissue** [comment]
Yes, you're right. The build is Pathfinder and this issue is caused by the missing of breakdown display. Therefore the calculation of poison duration is correct.
Thanks for the clarification.
