### ISSUE TITLE
[Feature Request] Add buttons for 'patch notes' and 'source project' to the main UI

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#14]
This is something that might be very usefull in this 'fast fixing/improving' days :D
Just a two small buttons, maybe above/below [Check for Update] button.

Clicking on [Patch Notes] brings up some popup/overlay windows with few (5 or so) latest versions and their notes. Also with a button to the full patchnotes of all versions (when you'll make some, instead on monkey-edditing readme :))
Clicking on [Source Project] will open up your projet's main page in browser.

**Comment by Openarl** [comment]
There is a changelog at the bottom of the main page of the GitHub project; I am planning to display patch notes inside the program at some point though. Likewise with the project page link.

**Comment by dein0s** [comment]
> There is a changelog at the bottom of the main page of the GitHub project

That's what I meant to be a 'monkey-editing readme.md' :D

**Comment by Openarl** [comment]
Oh right, read through your comment too quickly and missed that!
The irony is that the patch notes code which I just wrote and am currently testing, pulls the changelog from the README.md :D.

**Comment by dein0s** [comment]
What about using default 'release' functionality? Or it doesn't suits you somehow?

**Comment by Openarl** [comment]
Honestly I update too frequently for the releases page to be practical. I only intend to use that to distribute new installer versions, and since the program always installs the latest version regardless there's not even much need to put new versions up. This way, I add the patch notes in one place, run the script to prepare the update, commit and then it's out there! Easy peasy.

**Comment by dein0s** [comment]
Hmm, just 'git tag' then?
As far as I remember, anotated tags (with -a key) holds all your commit history with their comments.
Don't wanna be too much annoying or to teach you how to work, so don't get me wrong :D
It just seems awkward for me if you if you have to use some ad-hocs instead of builtin functionality.

**Comment by Openarl** [comment]
Honestly the entire update system for this program is a bit ad-hoc but hey, it works well! Regarding git tag, I wouldn't like my commit comments as a changelog since I tend to be a bit more terse and technical with them. Writing systems like this takes so little time regardless; in fact I've just pushed the update that contains it, so this feature request is officially closed! :D
