### ISSUE TITLE
Critical Strike not being calculated correctly?

### ISSUE THREAD

**Issue by myrahz** [Openarl/PathOfBuilding#158]
I have this build where I'm sitting on 80% crit, 625 % multiplier but Path of Building says I don't get any benefit from Critical Strike Chance? I get Critical Strike Chance nodes and my Crit Chance doesn't change neither my DPS.

Here's the build

http://pastebin.com/ifMSwDVJ

**Comment by Openarl** [comment]
The calculation is in fact correct. Unlike the in-game character sheet, Path of Building factors in your accuracy when calculating your crit chance.  In your case, your chance to crit is being capped at 95%, but your effective crit chance will be 80.75% due to your accuracy; so in that case, getting more crit chance nodes really will have no effect on your DPS. 

If you need to see your crit chance _without_ accuracy, you can either hover over your crit chance in the Calcs tab to see the breakdown of the calculation, or change the calculation mode in the Calcs tab to something other than Effective DPS (as the other modes are designed to match the output of the in-game tooltip and character sheet).

**Comment by myrahz** [comment]
Silly me.
