### ISSUE TITLE
Incorrect conversion for viper strike

### ISSUE THREAD

**Issue by MatthewSbar** [Openarl/PathOfBuilding#1676]
Something is either wrong in PoB or PoE or both, I'm not sure which.

The viper strike gem says in the description it adds phys as extra chaos ("adding some of your physical damage as chaos damage"), but in the gem tooltip it says it converts phys to chaos (50% of Physical Damage Converted to Chaos Damage) and says nothing about adding as extra

In PoB it says it adds as extra rather than converts.

**Comment by MatthewSbar** [comment]
Update: I was looking at viper strike from Arakaali's fang spiders. Now I'm not sure if SummonedSpiderViperStrike is fundamentally different than viper strike in terms of damage calculations or one of them just wasn't updated in PoB.

**Comment by Openarl** [comment]
The player and SummonedSpider versions of Viper Strike both have the correct stats (player has conversion to chaos, the other has added chaos). 

It does however appear that the player skill's description wasn't updated when it was changed from added chaos to conversion, which according to the wiki happened in the 2.1.0 patch nearly 4 years ago... But since PoB's description matches that shown in-game, then that's not my problem to fix (well, at least not in my capacity as PoB developer...)
