### ISSUE TITLE
Minion (Specifically Skeletons) & Generocity Support

### ISSUE THREAD

**Issue by Rocket-Fish** [Openarl/PathOfBuilding#169]
Are you planning to make Minion (specifically skeletons) and generocity support for auras any time soon (by that I mean the next 2-4 weeks). If you are not planning to do so, I would love to give it a try to make that functionality. 

Also are you using Microsoft Visual Studio for this? There is a .sln file, however Im not sure how I am supposed to compile and debug the thing if I make changes. Is there a plugin or something for lua?

** Note that I am not good with lua, but could probably pick it up.

**Comment by Openarl** [comment]
Minion support won't be coming any time soon, as there isn't really enough information available on how minion calculations work. I could conceivably add in health calculations (the program already does it for totems), but DPS calculations would be far more difficult, both due to the lack of information, and because there's no way to verify that the calculations are correct. You're welcome to try, though.

I do indeed use VS (with [NPL_LuaLanguageService](https://marketplace.visualstudio.com/items?itemName=Xizhi.NPLLuaLanguageService), although that's optional). Lua isn't compiled (well, not statically anyway); the source files are loaded and run directly. If you're looking to make changes, you have two options:

1. Edit the source files within your installation. If you used the installer (the .exe), you'll find them in "%ProgramData%\Path of Building". Once you make a change, you need to restart the program for it to take effect; after restarting it'll prompt to update, which will revert the changes, so ignore it.

2. Set up a development install. I haven't documented that process yet, but I recommend using this option for any serious development, so here's how:
- Clone the repository somewhere; it's best to clone the dev branch, as that's where changes are committed first.
- Extract runtime-win32-.zip into a different folder (outside the repository).
- Create a shortcut to the "Path of Building.exe" in the runtime folder, and add an argument containing the path and filename of the "Launch.lua" in the repository.
You can now use that shortcut to launch the program. It will take a while to start up for the first time, as it needs to download the passive tree data, which isn't kept in the repository. Running from the repository will automatically enable developer mode, which has a few handy debugging features; most notably, you can now use F5 to restart the program in-place.

**Comment by OSwoboda** [comment]
Are Minions going to be supported with the released spreadsheet which can be found [here](https://docs.google.com/spreadsheets/d/1LAi5g067lGa2XdHPpGa1ae8RKe-LBnwCjE-Z384fTV4/htmlview?sle=true#gid=1197252210)?

**Comment by Openarl** [comment]
I still need to actually add support for minion calculations, which is hardly straightforward. It's likely to be a few weeks at least before I get anything working, maybe longer.

**Comment by Openarl** [comment]
Added in 1.4.0.
Boy am I glad to finally close this one!
