### ISSUE TITLE
Cast speed for flameblast totems is broken for 1.3

### ISSUE THREAD

**Issue by boyangfu** [Openarl/PathOfBuilding#170]
cast speed will not modify dps nor cast rate in certain tree configurations, testing with a heirophant build

**Comment by Openarl** [comment]
This is something of a half-bug; due to the way attack/cast speed calculations work, it's possible to have configurations in which gaining 1 or 2% increased attack/cast speed doesn't change the attack/cast rate (this is the case both in PoB and in-game). However what's happening with 10 Stage Flameblast is a bit more extreme (even 6% nodes can have no effect), and definitely isn't intentional. I'll see if I can manage to fix it in the next update.

**Comment by Openarl** [comment]
I've found a fix for this; as of the next update, Flameblast's 10 Stages skill part will apply a 0.1 DPS multiplier rather than a 90% less Cast Speed modifier, which will fix this issue.
