### ISSUE TITLE
[Bug] Program breaks when taking off voidheart

### ISSUE THREAD

**Issue by kennynzhang** [Openarl/PathOfBuilding#181]
Hi,

I got the following stacktrace when taking off my voidheart during a long building session, and then changing anything (or at least any gear or passive skill tree points) gives the same error popup and no change in my stat summary on the left. Restarting the application fixes the issue, and the issue doesn't show up again when I tried taking my voidheart off again. 

![image](https://cloud.githubusercontent.com/assets/3814751/23199859/a6bc93e6-f896-11e6-900b-bd2860c6fa62.png)

**Comment by Openarl** [comment]
This was an interesting one to track down. It only occurs if you've pinned open breakdowns for poison or bleed, then switched to the items tab and unequipped an item that was granting poison or bleed chance. This bug would've been around since 1.2.0, but I'm not surprised no-one's managed to trigger it before, since it's so specific. Anyway, as usual it's fixed in the next update.
