### ISSUE TITLE
[Bug?] Caustic Arrow hit DPS affected by Conc Effect

### ISSUE THREAD

**Issue by at-kevinlau** [Openarl/PathOfBuilding#188]
Caustic Arrow's hit DPS (as opposed to the DoT DPS) should not be affected by AoE modifiers, per this post:
https://www.pathofexile.com/forum/view-thread/1642221/page/1#p13148879

To reproduce, try linking Concentrated Effect to Caustic Arrow.

(Additionally, poison caused by Caustic Arrow hits also seems to be affected by AoE modifiers.)

**Comment by Openarl** [comment]
The program actually has the same limitation that the game does: the DoT's "area damage" flag is inherited from the properties of the hit damage, so either both are area damage, or neither are. The game resolves this by not factoring in area damage in the DoT, I resolved it by making area damage apply to both.

That being said, I may be able to create a workaround. I'll look into it.

**Comment by Veracior** [comment]
Yeah the initial hit doesn't factor Area Damage (Conc. Effect) into its calculation in game, only the degeneration cloud does that. I am unsure how Poison would react to it though, could still be calculated when double dipping and include it?

**For @at-kevinlau:**
There are however a lot of cases of 'hidden' tags on gems where they might not say AoE or Duration but they benefit from less duration and concentrated effect all the same. For example [Burning Arrow](http://pathofexile.gamepedia.com/Burning_Arrow) is effected by [Less Duration](http://pathofexile.gamepedia.com/Less_Duration_Support)'s more multiplier even though it does not show a duration tag. 
This seems to be the case because of the threshold jewel [Pitch Darkness](http://pathofexile.gamepedia.com/Pitch_Darkness) which unlocks additional functionality in the burning arrow gem and for this reason, even without the threshold jewel equipped, burning arrow has a hidden duration tag.

**Comment by Openarl** [comment]
Ok, I found a workaround for this; it'll be fixed in the next update.
