### ISSUE TITLE
[Bug]Prim Eminence, golem buff on stone golem not working

### ISSUE THREAD

**Issue by Crazy-KSK** [Openarl/PathOfBuilding#198]
also is there a way to simulate more then one golem summoned?

Thanks for making the tool I dreamed of since I started playing! <3<3<3

**Comment by Openarl** [comment]
I haven't had time to add support for most of the modifiers on the Primordial jewels; the program doesn't do minion calculations anyway so most of them do nothing. I'll add the buff effect one though, since that's useful.

What do you mean by simulating more than one golem summoned? You can already have multiple golem skills active.

**Comment by Crazy-KSK** [comment]
summoning multiple of the same golem that is e.g. in brinerot mark

**Comment by Openarl** [comment]
Ah ok. You can have multiple copies of the skill active, although the buffs aren't handled correctly at the moment (both will apply); that's something I'm planning to fix though.

**Comment by Openarl** [comment]
Multiple copies of the same golem buff will be handled correctly as of the next update.
