### ISSUE TITLE
[Bug] Rigwald's Curse Interactions

### ISSUE THREAD

**Issue by jncrenshaw** [Openarl/PathOfBuilding#207]
On many levels, Rigwald's curse is not properly handled:

1. While Shield Charge/Unarmed gains a crit-chance after adding Rigwald's Curse to the items, the crit chance is far less than the stated "+7%" listed as an explicit property of Rigwald's curse
2. All passives in the tree allocated to boost Claws are NOT being included in DPS calculations for unarmed damage after equipping Rigwald's Curse.

In general, unarmed combat seems to be pretty buggy at the moment, but specifically the interactions with Rigwald's Curse makes trying to build around this now (more easily) accessible unique nigh unto impossible with PathOfBuilding.

**Comment by Openarl** [comment]
I haven't added support for the modifiers that apply claw stats to unarmed; that's why they appear red in the item tooltip. They're not straightforward to implement, but I'll try and take a look sometime today.

As for the base crit chance, as far as I can tell it's working fine. Do note that accuracy is factored into the crit chance calculation, so the crit chance may go up by less than 7% when equipping the talisman; check the breakdown for crit chance in the Calcs tab to verify.

**Comment by Openarl** [comment]
The next update will finally add support for Rigwald's Curse. Enjoy!

**Comment by jncrenshaw** [comment]
As always, great work! Your constant updates and communication are an inspiration to other developers! Big A+
