### ISSUE TITLE
[BUG] Conversion above 100%

### ISSUE THREAD

**Issue by Jinnai** [Openarl/PathOfBuilding#216]
When picking Physical to Lightning on a Wild Strike build the 50% Physical converted to Lightning is treated like added damage, instead of squishing the 150% conversion down to 100% so the build should have 33% Lightning and 67% of whatever element procced.

**Comment by Openarl** [comment]
This is an interesting case; the behaviour you're seeing may actually be intended, or could reflect a bug in the game, or it could be a bug in PoB...
As you are aware, conversions over 100% normally get scaled down; you may also be aware that skill conversions (such as that from Wild Strike or Physical to Lightning) always have priority over global conversions (from passives and items).
But what happens if the skill conversions themselves exceed 100%? Well, in theory they should be scaled down to 100%; however, and I don't know if this is intended or not, they currently _do not_ get scaled at all! You can verify this in-game if you have a character that has no elemental damage bonuses, using Molten Strike and a level 1 Physical to Lightning; with just the Molten Strike you'll see 60% of the physical as fire, and when you add PtoL you get 60% as fire and 60% as lightning (50% converted, 10% added).
Nevertheless, PoB's behaviour might not be correct for Wild Strike, due to another issue with the game. Some skills incorrectly use global conversion instead of skill conversion; Burning Arrow and Frost Blades are two examples. But Wild Strike's conversion isn't in the game data (as far as I can tell), so I don't know whether it uses the correct type. Once the patch arrives I can test that though, since the conversion went up to 100%.

**Comment by Openarl** [comment]
I've checked now, and Wild Strike uses global conversion; so I'll fix that in the next update.
