### ISSUE TITLE
[bug]updating bricked PoB

### ISSUE THREAD

**Issue by Crazy-KSK** [Openarl/PathOfBuilding#228]
I clicked update after saving my build, the change log window was empty, upon updating this error appeared and persists though restarts
since I remember updating to the latest version earlier I must have gotten some kind of ghost update
http://i.imgur.com/OwvWuSl.jpg
that file is indeed missing

manual reinstall fixed it

**Comment by Openarl** [comment]
I'm struggling to figure out how this could have happened.

The update system works by synchronising the files in your installation with those here on GitHub, using the version manifest file as a reference. The only time a file would be deleted is if it longer appears in the manifest, but that couldn't have happened in your case because the manifest hadn't been changed for a few days. Yet the fact that it prompted for an update at all means something _must_ have changed, somehow.

It would be useful to know if any other files had disappeared; I don't suppose you kept the original installation?

**Comment by Crazy-KSK** [comment]
Afraid not. =(
As far as I can tell it must have been the 1.3.19 update giving me the update available.
I could imagine windows not giving write permission because of the file still being in use, I get that all the time updating PoE, but deleting a file that hasn't changed in several days is just weird.  
In any case if it happens again I will sent you the broken version.

**Comment by Openarl** [comment]
1.3.19 hadn't been released yet, so that wasn't it. The program also doesn't keep any of its files open while running (except for the binaries, which are rarely updated); so there should never be any problems writing to files.

I'm not sure I'll be able to solve this one without being able to examine the broken version (particularly the local version manifest file).

**Comment by Openarl** [comment]
Well I haven't had any further reports of anything like this happening, so I'll just put this down as a one-off fluke.
