### ISSUE TITLE
Berek's Grip, Two Stone Ring Damage Miscalculation

### ISSUE THREAD

**Issue by grillinterrupted** [Openarl/PathOfBuilding#246]
I have a character with only added lightning from BG ring saved and the damage is visible in the calc section. Any attempt to create a completely new build, adding the BG ring will not get any added lightning for some reason.  Below is an album detailing the issue: http://imgur.com/a/s53qy

**Comment by grillinterrupted** [comment]
deleting the ring and the adding it again fixed the damage miscalculation, somehow

**Comment by Openarl** [comment]
There was actually a bug here, but it's not straightforward:
1) Several uniques, including Berek's Grip, had "Adds x-x X Damage to Spells and Attacks" stats added in 2.6.0, which had not previously appeared on any items
2) My handling of that new stats were flawed, and was causing the added damage to never apply; that's fixed in the next update
3) Re-adding the item from the unique database fixed it, because that version used a different wording that _was_ working; the 2.6.0 patch notes weren't clear on the wording that would be used for these stats, so I made a conservative guess (which turned out to be incorrect); that has also been fixed in the next update
