### ISSUE TITLE
[BUG] Skills imported multiple times despite the match

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#25]
Steps:
1 Imported whole profile (tree+jewels and items+skills)
1.1 Saved changes
2 On skills tab I have following skill chain
![skill chain](http://i.imgur.com/mEnwHyn.png)
3 Import same profile once again (only items+skills), skill chain duplicated (same gems, same level and quality, same order, same item)
![second skill chain](http://i.imgur.com/wRONZp0.png)

Additional info: character [mommysPIZZAMAKER](https://www.pathofexile.com/account/view-profile/dein0s/characters)

**Comment by Openarl** [comment]
The code that checks if a skill chain is already present in a build was being tripped up by a difference in capitalisation: the program's gem database had "Curse on Hit" whereas the gem's actual name is "Curse On Hit". I love bugs like this :). This is fixed in the next update. Thanks for the report!
