### ISSUE TITLE
[FR] add dps calc to molten burst 

### ISSUE THREAD

**Issue by mindyk** [Openarl/PathOfBuilding#280]
atm the molten burst dmg calc does not include any dps

**Comment by Openarl** [comment]
How can the program possibly know how often it will hit?

**Comment by mindyk** [comment]
hit? or trigger? idk how you calculate the magma ball dmg of molten strike but i would argue the "hit" calculation would be rather similar. 

trigger -> attack rate of main attack / 5 = avg trigger rate?

**Comment by Openarl** [comment]
Molten Strike is easy, since the magma balls and melee hit are part of the same skill. But for Molten Strike, the program would need to know what skill is being used to trigger it, and also calculate its hit rate while doing the calculations for Molten Burst. Neither is currently possible, given the program's design.

**Comment by mindyk** [comment]
i see, thx for clearing that up
