### ISSUE TITLE
running with wine

### ISSUE THREAD

**Issue by ccomly** [Openarl/PathOfBuilding#287]
Sorry if this is the wrong place to ask.

Has anyone gotten this to work with wine? iv been trying a few different configurations but nothings working yet.

**Comment by dein0s** [comment]
Maybe #28 will give you some ideas.
Nevertheless, PoB is supposed to run only on truly Windows environments atm.

**Comment by tarpan2** [comment]
Is there a way to load custom dlls like the SimpleGraphic.dll into playonlinux maybe?

**Comment by kazuoteramoto** [comment]
I could never get PoB to work on wine. Its always crash on simplegraphic.
This is backtrace.txt
```
Unhandled exception: page fault on read access to 0x6365746f in 32-bit code (0x0033bf73).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0033bf73 ESP:0032e3bc EBP:0032e3c8 EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:00000003 EBX:00000000 ECX:6365746f EDX:00000000
 ESI:00441728 EDI:0000001c
Stack dump:
0x0032e3bc:  7eccc000 0002005c 0032e974 0032e3f8
0x0032e3cc:  7ec8b5aa 0002005c 0000001c 00000000
0x0032e3dc:  00000000 0033bed0 0002005c 00000047
0x0032e3ec:  7eccc000 0032e974 0002005c 0032e448
0x0032e3fc:  7ec8bc1a 0033bed0 0002005c 0000001c
0x0032e40c:  00000000 00000000 7eccc000 0032e448
Backtrace:
=>0 0x0033bf73 in simplegraphic (+0xbf73) (0x0032e3c8)
  1 0x7ec8b5aa WINPROC_wrapper+0x19() in user32 (0x0032e3f8)
  2 0x7ec8bc1a in user32 (+0x9bc19) (0x0032e448)
  3 0x7ec8c0c6 in user32 (+0x9c0c5) (0x0032e908)
  4 0x7ec8e114 in user32 (+0x9e113) (0x0032e948)
  5 0x7ec506de in user32 (+0x606dd) (0x0032e9b8)
  6 0x7ec57654 in user32 (+0x67653) (0x0032ea18)
  7 0x7ec578f0 SendMessageW+0x5f() in user32 (0x0032ea68)
  8 0x7ec32de7 in user32 (+0x42de6) (0x0032eb78)
  9 0x7ec332cc SetActiveWindow+0x7b() in user32 (0x0032ebb8)
  10 0x7ec86374 in user32 (+0x96373) (0x0032ec08)
  11 0x7ec88529 in user32 (+0x98528) (0x0032ec88)
  12 0x7ec88618 ShowWindow+0x47() in user32 (0x0032eca8)
  13 0x0033cf68 in simplegraphic (+0xcf67) (0x0032ecf4)
  14 0x0033c7e0 in simplegraphic (+0xc7df) (0x0032ef30)
  15 0x00344939 in simplegraphic (+0x14938) (0x0032ef60)
  16 0x0040167b in path of building (+0x167a) (0x0032fdac)
  17 0x00401b1f in path of building (+0x1b1e) (0x0032fe40)
  18 0x7b460d3c call_process_entry+0xb() in kernel32 (0x0032fe58)
  19 0x7b461d24 ExitProcess+0xfe3() in kernel32 (0x0032fe98)
  20 0x7bc81d2c call_thread_func_wrapper+0xb() in ntdll (0x0032feb8)
  21 0x7bc84cff call_thread_func+0xce() in ntdll (0x0032ffa8)
  22 0x7bc81d0a RtlRaiseException+0x21() in ntdll (0x0032ffc8)
  23 0x7bc53c33 call_dll_entry_point+0x3d2() in ntdll (0x0032ffe8)
  24 0xf7550dad wine_call_on_stack+0x1c() in libwine.so.1 (0x00000000)
  25 0xf7550f10 wine_switch_to_stack+0x1f() in libwine.so.1 (0xff9e6758)
  26 0x7bc59b22 LdrInitializeThunk+0x251() in ntdll (0xff9e67a8)
  27 0x7b467f20 __wine_kernel_init+0xa5f() in kernel32 (0xff9e7918)
  28 0x7bc5aa03 __wine_process_init+0x152() in ntdll (0xff9e7988)
  29 0xf754efe7 wine_init+0x2c6() in libwine.so.1 (0xff9e79e8)
  30 0x7c000a82 main+0x81() in <wine-loader> (0xff9e7e38)
  31 0xf7382366 __libc_start_main+0xf5() in libc.so.6 (0x00000000)
0x0033bf73: movl	0x0(%ecx),%edx
Modules:
Module	Address			Debug info	Name (68 modules)
PE	  330000-  3e9000	Export          simplegraphic
PE	  400000-  43c000	Export          path of building
PE	10000000-10057000	Deferred        lua51
ELF	7a800000-7a936000	Deferred        opengl32<elf>
  \-PE	7a820000-7a936000	\               opengl32
ELF	7b400000-7b7e1000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b7e1000	\               kernel32
ELF	7bc00000-7bcf8000	Dwarf           ntdll<elf>
  \-PE	7bc10000-7bcf8000	\               ntdll
ELF	7c000000-7c004000	Dwarf           <wine-loader>
ELF	7e0f1000-7e115000	Deferred        imm32<elf>
  \-PE	7e100000-7e115000	\               imm32
ELF	7e249000-7e273000	Deferred        libexpat.so.1
ELF	7e273000-7e2bd000	Deferred        libfontconfig.so.1
ELF	7e2bd000-7e336000	Deferred        libpcre.so.1
ELF	7e336000-7e461000	Deferred        libglib-2.0.so.0
ELF	7e461000-7e4ed000	Deferred        libharfbuzz.so.0
ELF	7e4ed000-7e52b000	Deferred        libpng16.so.16
ELF	7e52b000-7e544000	Deferred        libz.so.1
ELF	7e544000-7e60c000	Deferred        libfreetype.so.6
ELF	7e60c000-7e67a000	Deferred        libncursesw.so.6
ELF	7e6ac000-7e784000	Deferred        msvcr100<elf>
  \-PE	7e6c0000-7e784000	\               msvcr100
ELF	7e784000-7e7fc000	Deferred        shlwapi<elf>
  \-PE	7e790000-7e7fc000	\               shlwapi
ELF	7e7fc000-7ea41000	Deferred        shell32<elf>
  \-PE	7e810000-7ea41000	\               shell32
ELF	7ea41000-7eab8000	Deferred        advapi32<elf>
  \-PE	7ea50000-7eab8000	\               advapi32
ELF	7eab8000-7ebe0000	Deferred        gdi32<elf>
  \-PE	7eac0000-7ebe0000	\               gdi32
ELF	7ebe0000-7ed36000	Dwarf           user32<elf>
  \-PE	7ebf0000-7ed36000	\               user32
ELF	7ef36000-7ef49000	Deferred        libnss_files.so.2
ELF	7ef49000-7ef57000	Deferred        libnss_nis.so.2
ELF	7ef57000-7ef72000	Deferred        libnsl.so.1
ELF	7ef72000-7efce000	Deferred        libm.so.6
ELF	7efd5000-7efe6000	Deferred        libbz2.so.1.0
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f6e17000-f6e1e000	Deferred        libxfixes.so.3
ELF	f6e1e000-f6e29000	Deferred        libxcursor.so.1
ELF	f6e29000-f6e3c000	Deferred        libxi.so.6
ELF	f6e3c000-f6e49000	Deferred        libxrandr.so.2
ELF	f6e49000-f6e55000	Deferred        libxrender.so.1
ELF	f6e55000-f6e5c000	Deferred        libxxf86vm.so.1
ELF	f6e5c000-f6e87000	Deferred        libxcb.so.1
ELF	f6e87000-f6fd4000	Deferred        libx11.so.6
ELF	f7006000-f7093000	Deferred        winex11<elf>
  \-PE	f7010000-f7093000	\               winex11
ELF	f7093000-f70be000	Deferred        msacm32<elf>
  \-PE	f70a0000-f70be000	\               msacm32
ELF	f70be000-f713f000	Deferred        rpcrt4<elf>
  \-PE	f70d0000-f713f000	\               rpcrt4
ELF	f713f000-f7278000	Deferred        ole32<elf>
  \-PE	f7160000-f7278000	\               ole32
ELF	f7278000-f7331000	Deferred        winmm<elf>
  \-PE	f7280000-f7331000	\               winmm
ELF	f7333000-f7338000	Deferred        libdl.so.2
ELF	f7340000-f7347000	Deferred        libxdmcp.so.6
ELF	f7347000-f734b000	Deferred        libxau.so.6
ELF	f734b000-f7360000	Deferred        libxext.so.6
ELF	f7360000-f736a000	Deferred        libnss_compat.so.2
ELF	f736a000-f752a000	Dwarf           libc.so.6
ELF	f752a000-f7548000	Deferred        libpthread.so.0
ELF	f7548000-f76ff000	Dwarf           libwine.so.1
ELF	f7701000-f7726000	Deferred        ld-linux.so.2
ELF	f7728000-f7729000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\home\kazuo\tmp\PathOfBuilding-1.3.25\Path of Building.exe
	0000003d   -1
	00000009    0 <==
0000000c services.exe
	00000037    0
	00000036    0
	00000033    0
	00000032    0
	0000000e    0
	0000000d    0
00000012 explorer.exe
	00000016    0
	00000013    0
00000034 winedevice.exe
	0000003c    0
	0000003b    0
	0000003a    0
	00000039    0
	00000038    0
	00000035    0
System information:
    Wine build: wine-2.4
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 4.10.9-1-ARCH
```

**Comment by terminull** [comment]
Damn, was hoping this would work. Only alternative for mac I see is to run a VM/bootcamp.

**Comment by Chadderz121** [comment]
Well, it's a horrible hack but I did manage to get it working (Wine 2.12, Ubuntu 14.04, no special config, blank prefix). The only thing that prevented it working is SimpleGraphic.dll. #28 includes the source code for this which helped me track it down. The problem is `ShowWindow` (called at `engine/system/win/sys_video.cpp:101`) in Wine triggers the message `WM_ACTIVATEAPP` which is handled at `engine/system/win/sys_main.cpp:466`. I guess Windows doesn't do this though, because at the time this message is sent `sys->video` is uninitialised, and won't be initialised until `sys_video_c::sys_video_c` returns. Hence the page fault, accessing this uninitialized pointer. I don't know if the 'blame' lies with Wine or with SimpleGraphic.dll, I guess we'd need to inspect the specification for `ShowWindow` to see if the assumption that it doesn't send `WM_ACTIVATEAPP` is valid or not.

I'm not set up to compile SimpleGraphic.dll right now though, so here comes the horrible hack, I've manually edited the assembly code in the dll to reorder the calls to `SetWindowLongPtr` and `ShowWindow` which helpfully prevents the page fault from happening by triggering an earlier if condition in `sys_main.cpp`. If you trust my handiwork, feel free to replace your SimpleGraphic.dll with [this one](https://github.com/Openarl/PathOfBuilding/files/1240326/SimpleGraphic.zip). The updater may replace SimpleGraphic.dll, so be sure to replace it back if it updates.

**Comment by kazuoteramoto** [comment]
Its work! Thanks @Chadderz121 . I tested it on wine 2.15. On Arch Linux I also needed to install `lib32-libldap` and `lib32-gnutls`.

PoB always show a "Update Ready", even after a successful update. I think because the hash in `manifest.xml` don't match the hash of the modified `SimpleGraphic.dll`. But, everthing seen to be working correctly.

**Comment by Openarl** [comment]
The next update (1.4.64) will change the way the program initialises the window and renderer; the window creation no longer occurs during sys_video_c::sys_video_c(), but is instead deferred to ::Init(), which is now called earlier so that OpenGL initialises after the window has been properly positioned and styled. This is primarily aimed at fixing #336 and #527, but it will also remove the need for @Chadderz121's workaround, and hopefully allow the program to run under wine without issue.

**Comment by kazuoteramoto** [comment]
I tried the new update (1.4.64) with wine 2.18. Its seen to work nice. Sometime I get an unresponsive window with patches of black on start but resizing (forcing a redraw?) fix it.

Thanks!

**Comment by lawrenz1337** [comment]
@kazuoteramoto Hey there, I also use arch linux, can you give a short tutorial how the get PoB to work? Do I use portable/installer version?

**Comment by zmike** [comment]
This ticket should be closed. The installer for PoB doesn't work under wine, but the binary from the zip folder works without issues out of the box.

**Comment by Openarl** [comment]
Yeah, probably time to close this, as I haven't heard of any issues with wine now.

**Comment by berserkingyadis** [comment]
After downloading the latest release of PathOfBuilding and starting it with wine 3.4 there is this error
![Image of the error](https://i.imgur.com/YOOdH6y.png)
The file lcurl.dll exists in the directory, strange.

**Comment by berserkingyadis** [comment]
@Openarl can we reopen this? Currently trying to figure out whats wrong

**Comment by berserkingyadis** [comment]
Update: its working again, last changes may have fixed it.

**Comment by beelzebielsk** [comment]
I've got a question, not sure if this is right place to ask them:

- Does POB write in the windows registry or outside of it's directory (if run as the standalone zip)?

I'm asking because I'd like to make a package for my Linux distribution for POB (my distro is Arch Linux), and the way to package this depends on the answer to that question.

I can see that standalone POB writes files into its own directory, into the Builds folder, at a minimum.

**Comment by xolan** [comment]
@beelzebielsk It's packaged on Lutris https://lutris.net/games/path-of-building/ . Maybe you can build on that.

**Comment by beelzebielsk** [comment]
@xolan Hadn't heard of Lutris before. Thanks.
