### ISSUE TITLE
[BUG] Shaper's Glove bonuses not working.

### ISSUE THREAD

**Issue by Mamotromico** [Openarl/PathOfBuilding#29]
The special bonuses like Evasion per Int, Melee Phys per Dex, etc, don't seem to be working.

I'm on a CI tree, so maybe it breaks the bonuses application dues to not being able to receive one of the bonuses ( +1 life per dex)?

**Comment by Openarl** [comment]
The program currently doesn't handle per-stat bonuses from items at all. They're a little tricky to do for technical reasons, but per my SOP since you've asked for it I'll try and get it done sooner rather than later. :)

**Comment by Mamotromico** [comment]
Thank you :D

I'll try to setup my VS here so I can see how hard it is to add those missing calculations. I just noticed that white mods on item are the ones that are not being taken into account. There's a bunch I'm interested on trying out, so I figured I could help trying to fix it.

**Comment by sabromex** [comment]
Whoops, just submitted an issue about this problem. Would love to see this implemented. Also, since I'm here, the Winter's Touch skill Icestorm doesn't appear when calculating skill gem damage.

**Comment by Openarl** [comment]
Your timing is impeccable, because I've just finished adding support for both Icestorm and the Shaper's Touch modifiers. You'll have to wait a little longer though, because that support relies on the overhaul of the program's internal modifier system that's coming with the next major update (1.2.0). I've still got a fair bit of work to do on that update (the Calcs tab got completely broken, so I'm reworking it from scratch), but if you're lucky I could have it out within the next week.

**Comment by Openarl** [comment]
Support added in patch 1.2.0.
