### ISSUE TITLE
Crit Chance lowers Total DPS with elemental overload

### ISSUE THREAD

**Issue by bane2571** [Openarl/PathOfBuilding#323]
I'm using a character with Elemental Overload. Account: bane2571 Character: poloniusthesilent

With that passive tree I'm looking at adding king of the hill but it is reporting that I would lose DPS by doing so. I've also tried using the accuracy and crit chance nodes which, given the Lioneye's bow, should only affect crit chance and the DPS also decreases.

Given that it might be calculating a 100% up time at 15% crit (which I doubt is true), worst case adding more crit% should do nothing. Why is it decreasing the estimated DPS?

PS: damn this program is awesome, the fact that I can immediately tell something weird is going on in the calcs shows how much normally invisible info you're providing to players - kudos.

**Comment by Openarl** [comment]
The program always assumes 100% uptime on Elemental Overload, as that's usually quite easy to achieve.

You have no crit multiplier, so the difference between your crit and non-crit damage is entirely determined by the enemy's resistances. And since you have Inevitable Judgement, your crit damage is calculated as if the enemy's resistance is 0, but your non-crits use the normal calculation (enemy resistance minus penetration). 

Therefore, if your penetration would reduce the enemy's resistance to below 0, then your non-crits will deal more damage than your crits, and so gaining more crit chance really will lower your DPS. If on the other hand the enemy's resistance ends up positive (which in your case would be true against any boss), then more crit chance increases your DPS slightly.

**Comment by bane2571** [comment]
Wow, the interaction on inevitable judgement - I had no idea the neg resistance=neg damage potential even existed. Good news is you have a enemy resistances option - after filling that in for merciless (45%), king of the hill now gives +dps instead of -dps. 

Thanks!
