### ISSUE TITLE
Path of Building has stopped working

### ISSUE THREAD

**Issue by PhilMonster** [Openarl/PathOfBuilding#328]
im running Win 10 and PoB worked fine, today i installed the Win 10 Creators update and since then every time i tried to open PoB it just crashes and i get the message "Path of Building has stopped working"
![pob has stopped working](https://cloud.githubusercontent.com/assets/14953485/25558461/92424d00-2d27-11e7-86a5-4a5c2ff331a3.PNG)

**Comment by djrecipe** [comment]
I am also using Windows 10 x64.. I didn't install any creators update. I just tried opening Path of Building this morning and it doesn't work.

I tried uninstalling, cleaning all files, trying standalone vs installed version, and I cannot get it to work.

**Comment by PhilMonster** [comment]
so the Creators update seems to not be the problem. thats wierd. why should it stop working all of the sudden?

**Comment by djrecipe** [comment]
Just tried it on my laptop and it is working fine there. I think this might be Windows update related? 

Sent from my phone
-------- Original message --------From: PhilMonster <notifications@github.com> Date: 4/30/17  1:19 PM  (GMT-08:00) To: Openarl/PathOfBuilding <PathOfBuilding@noreply.github.com> Cc: JD Pierce <brkfstmnchr@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Openarl/PathOfBuilding] Path of Building has stopped working (#328) 
so the Creators update seems to not be the problem. thats wierd. why should it stop working all of the sudden?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Openarl/PathOfBuilding","title":"Openarl/PathOfBuilding","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Openarl/PathOfBuilding"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PhilMonster in #328: so the Creators update seems to not be the problem. thats wierd. why should it stop working all of the sudden?"}],"action":{"name":"View Issue","url":"https://github.com/Openarl/PathOfBuilding/issues/328#issuecomment-298254453"}}}

**Comment by PhilMonster** [comment]
it works fine on my Laptop to but it also has Win 10 x64, but not Nvidia Geforce Expirience, since it dosent habe a Graphics card.

**Comment by PhilMonster** [comment]
The latest Update for Nvidia GeForce Expirience fixes this issue, and i can finaly use PoB again :D

**Comment by Openarl** [comment]
Ah, excellent. Quite a few people were experiencing this, so it's good to know Nvidia have finally managed to correct the issue.
