### ISSUE TITLE
Username with "ö" in name is not importable

### ISSUE THREAD

**Issue by Basoeckn** [Openarl/PathOfBuilding#344]
I can not import character from my account "Barsöckn", because the "ö" is not in the character set, as it will instantly become a "?" if you type it in.
Using my POESESSID does not work either, i guess because the username is still not usable

THanks in advance for your help

**Comment by Openarl** [comment]
As per #258, non-ASCII characters in the account name have to be replaced with their [URL encoding](https://www.urlencoder.org/), so your account name becomes:
Bars%C3%B6ckn

The root cause of this issue is the program's lack of Unicode support, which unfortunately isn't easy to fix. I probably aught to put a note about this in the import section, though...
