### ISSUE TITLE
Additional Accuracy Undeniable Stack Overflow

### ISSUE THREAD

**Issue by theshadedone** [Openarl/PathOfBuilding#347]
Hi,

When using the juggernaut node undeniable, and the accuracy gem, mousing over the modifiers to attack speed in the calculation tab causes a stack overflow error.

Probably not a major issue, but could help you find other problems.

Love your work,
    Theshadedone

**Comment by Openarl** [comment]
I can't manage to reproduce this exact case, but I presume this is the same overflow error that's been appearing since the last update; I've already fixed it for the next update, which will be out shortly. Anyway, the error message should stop appearing if you close and reopen the build, assuming it's the same error.
