### ISSUE TITLE
Pariah Ring Problem

### ISSUE THREAD

**Issue by xommander** [Openarl/PathOfBuilding#353]
Character Example - account StiquxD2
ChemPlaySRS

Pariah doesnt add the 100 flat es for having a blue socket if you select a blue gem to be socketed in it

**Comment by Openarl** [comment]
The program doesn't currently support any modifiers that interact with an item's sockets, mainly because it lacks the ability to display or edit an item's socket/link configuration. I have no idea when I'll be getting around to adding that; it won't be trivial to do, and I have more important things to work on at the moment.

**Comment by livejamie** [comment]
This is still happening. I can manually create the conditions on the ring but I don't know if it is still as difficult as you envisioned previously.

**Comment by Openarl** [comment]
The next update finally adds support for viewing and editing item sockets, as well as adding support for item modifiers that interact with the item's sockets, such as those on The Pariah.
