### ISSUE TITLE
Creating custom flask causes crash

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#374]
When I click "Create custom..." and then paste this...
```
Experimenter's Diamond Flask of Staunching
Crafted: true
Prefix: FlaskIncreasedDuration2
Suffix: FlaskRemovesBleeding1
Quality: 20
LevelReq: 27
Implicits: 0
{range:0.5}(30-40)% increased Duration
Immunity to Bleeding during Flask effect
Removes Bleeding on use
````

it crashes the program with the following error:

![image](https://cloud.githubusercontent.com/assets/510805/26769157/325a2b58-4972-11e7-8818-a45ae45d6b20.png)

Version 1.4.18

**Comment by Openarl** [comment]
That item is missing the rarity specification (Rarity: Magic), which is preventing the item parser from recognising the item correctly. That shouldn't be causing a crash though; that's fixed in the next update.

I have to ask though, why are you creating an item this way? I assume you got that item text from the "Edit..." dialog, and are attempting to duplicate the item? It would be much easier to just copy and paste the item directly.

**Comment by aggixx** [comment]
Yes, I copied the text from the "Edit..." dialog of an already existing item.

**Comment by Openarl** [comment]
Right; but you do know that you can just select the item and press Ctrl+C to copy it, rather than going to the trouble of opening the Edit dialog?

**Comment by aggixx** [comment]
Did not know that, nor do I know how you're supposed to figure that out.
