### ISSUE TITLE
[Feature Request] Add support of Toxic Delivery

### ISSUE THREAD

**Issue by chachazero** [Openarl/PathOfBuilding#39]
There is no change from allocating/unallocating Toxic Delivery right now.
I think this one will be popular very soon because people want to try Assassin + Blade Flurry.
Thanks for the work!

**Comment by Openarl** [comment]
The "100% more poison damage on crit" modifier on Toxic Delivery is a massive pain to implement, which is why I haven't gotten around to it yet. But the squeaky wheel gets the grease, so I'm going to roll up my sleeves and get to work on it.

**Comment by Openarl** [comment]
I think I have this working now. Figuring out how to simulate it was tricky, but hopefully I've got it right. I'm calculating a separate crit effect modifier for poison's base damage, and the Toxic Delivery modifier doubles the crit multiplier in that calculation. I'll be pushing out an update shortly that'll contain this change.

**Comment by chachazero** [comment]
Wouldn't adding a slightly different "more modifier" (100% * crit chance) into Total More section of poison be easier? The benefit is this might also give users a idea about how Toxic Delivery works. 
I don't know the structure so maybe I'm totally wrong.
Again, thanks for the work!

**Comment by Openarl** [comment]
That method doesn't accurately simulate the DPS increase of Toxic Delivery, as the poison damage doesn't increase linearly with crit chance. Here's an example:

Let's say your character deals 100 physical+chaos damage on a non-crit and 500 physical+chaos damage on crit, and has a 75% crit chance.
The average damage would be:
(100 + (500 - 100) * .75) = 400
If we just increase that by 75%, we get 700. But is that correct?
With Toxic Delivery, the damage on crit would effectively be 1000 (since it is doubled)
So the average becomes:
(100 + (1000 - 100) * .75) = 775
Which is 93.75% more. Since the difference will be dependant on the crit multiplier, in order to simulate it correctly, we need to recalculate the crit effect modifier.

As I said, tricky! :)

**Comment by chachazero** [comment]
Yeah, you're correct. Thanks for the explanation!
