### ISSUE TITLE
[Feature Requests / Bugs?] Assassin's Mark

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#40]
Hey!

Thanks again for your awesome work and the "Save as..." Button! ;)

I am playing around with Crit-Builds atm and I am noticing some weird behaviour / missing features with Assassin's Mark.

It seems as if the Increased Critical Strike chance is calculated correctly and is added to the "overview" on the left side of the app as well as under "Calcs". It's missing in the overview though. (see screen)

The "20% increased damage from critical strikes" (I think it's an effective 20% "more" multiplier for the crit multiplier) seems to be completely missing in the calculation of the damage / multiplier. Would be cool if we had these! ;)

![assassins_mark](https://cloud.githubusercontent.com/assets/7581754/20499267/0b97de32-b031-11e6-827b-6bd059ec7ce4.png)

**Comment by Openarl** [comment]
The extra crit chance from Assassin's Mark doesn't show in the modifier list because it's an enemy modifier, not a player modifier. It should be included in the calculation breakdown though; I'll fix that. I'll add an enemy modifier section too.

Regarding the "increased extra damage from Critical Strikes", when I initially added Assassin's Mark to the program, I didn't add support for that because I needed to find out how it functioned; it looks like I never got around to doing that. I'll see if I can get that sorted now.

**Comment by Openarl** [comment]
All done! I'll push out an update soon with these fixes.
