### ISSUE TITLE
Shock Nova and Decay

### ISSUE THREAD

**Issue by jobsonita** [Openarl/PathOfBuilding#406]
I've tested various skills (Fire Nova Mine, Vortex, Ice Nova, and Shock Nova itself) with Decay, using the same setup (Skill + Decay + Rapid Decay + Void Manipulation), both on Path of Building and on the actual game. Path of Building says that Shock Nova has 20% of the other skills Decay DoT, probably due to the "Ring deals 80% less Damage" part of Shock Nova. However, after testing it in the game, Shock Nova seems to have the same Decay DoT as the other skills I've tested.

**Comment by Openarl** [comment]
I don't actually know whether the less Damage multiplier on the ring is supposed to apply to Decay, and since anything that gets hit by the ring also gets hit by the nova (which deals full Decay DPS), you can't actually test it. Either way, if you change the skill part to "Nova" you'll get the correct Decay DPS.

**Comment by jobsonita** [comment]
Oh, damn, I've never noticed that option to change between "Ring" and "Nova". I must be blind. XP
