### ISSUE TITLE
[Bug] Reave stages not increasing radius

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#427]

**Comment by Openarl** [comment]
I can't reproduce this. Note that you need to select the stage count for Reave in the Calcs tab itself (not the sidebar) for the radius calculation to change.

**Comment by JYshadow** [comment]
I see, but then what is the stage count in de sidebar for?

**Comment by Openarl** [comment]
The stages are implemented using the program's skill part system. For most skills, different parts have different DPS, but Reave is one of the few exceptions; the skill part selector still appears in the sidebar anyway, despite not influencing the sidebar stats, because that's just how that system is designed.

**Comment by JYshadow** [comment]
All right, thanks
