### ISSUE TITLE
Error with Damage Conversion 

### ISSUE THREAD

**Issue by squidyj** [Openarl/PathOfBuilding#431]
Using the Beta Game Version, running Physical To Lightning with Glacial Cascade converts 110% of physical damage.

**Comment by Openarl** [comment]
That is actually working as intended; at least in the sense that Path of Building's behaviour matches that of the game.

Here's the in-game damage for a level 1 Glacial Cascade on a Beta character with no cold damage modifiers and 60% increase Physical Damage:
![overconvert1](https://user-images.githubusercontent.com/19189971/27761492-31e6fff0-5ea0-11e7-8c15-8b5fce140db8.png)
As expected, the 48 to 72 base Physical Damage becomes 77 to 115, split 40:60 between Physical and Cold.
Now with a level 1 Physical to Lightning Support added:
![overconvert2](https://user-images.githubusercontent.com/19189971/27761510-971603ee-5ea0-11e7-9f11-14f8fdb6f69f.png)
Note that the Cold Damage is unchanged, so we're still getting 60% of base Damage as Cold, and there's now an equal amount of Lightning Damage, so we're getting 60% of base Damage as Lightning too. But a level 1 Physical to Lightning only gives 10% of Physical as Extra Lightning Damage, so that means that both the skill's implicit 60% conversion _and_ the 50% conversion from the support are both applying at full value.

The same thing happens when Physical to Lightning is paired with a few other skills that have an implicit conversion of more than 50% (such as Static Strike and Molten Strike), but not all skills with such a conversion are affected (and the fact that some aren't is actually the product of another bug.) Conversions from other sources (e.g items) aren't affected either, and are always handled correctly.

I'm fairly sure that the game's behaviour in this case isn't correct, as GGG have said before that skill conversions are scaled down; I reported it 6+ months ago when I first encountered it, but it still exists in both live and beta versions of the game.
