### ISSUE TITLE
[Enhancement] Copy Class & Ascendancy when making a new passive tree

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#433]
With the ability to have multiple different passive trees saved in 1 PoB profile, I think it makes sense for passive trees created with the "New" button in the Manage Passive Trees dialogue to default to the same class & ascendancy as the topmost profile. While someone certainly may want to make a tree of a different class or ascendancy, that should be the minority of cases and even so it will still take them the same amount of time to change the tree's class as it would in the current setup (since it defaults to Scion).

**Comment by Openarl** [comment]
I'm usually pretty apprehensive about changing default behaviour, since at present, any time you see a new tree it's always Scion (ironically the least-played class). However those lovely class background artworks make it pretty darn obvious which class is currently selected, so I suppose there's no harm in this.
