### ISSUE TITLE
[Bug] "Spectral Spirits" and "Melee Damage on Full Life Support"

### ISSUE THREAD

**Issue by Jibblies** [Openarl/PathOfBuilding#436]
Hey Openarl,

first of amazing work with this program. :) Thanks a lot for it. I just wanted to ask if there is maybe an issue with the interaction between "Spectral Spirits" and "Melee Damage on Full Life Support". If i am not totally wrong then the MORE multiplier should work but it doesn't in PoB. Am i missing something? Spectral Spirits should always be on full life and it's not limited to weapons.

I hope it's really an unknown bug and not just a waste of your time here. Maybe it's just not implemented cause there is no "Minion is always on Full Life" option.

**Comment by Openarl** [comment]
The program never assumes that conditions like Full Life are true unless they are guaranteed to be so, and typically relies on user input in such cases; but, as you mentioned there's no Full Life option for minions. However, since these minions are immune to damage, I will enable the Full Life condition for them, since it is easily done.
