### ISSUE TITLE
[Bug] Int node not included in radius for threshold jewel

### ISSUE THREAD

**Issue by chuson** [Openarl/PathOfBuilding#444]
Hey guys, love POB just wanted to give back with a bug report. I noticed a bug with an int node between the Witch and Scion starting area.

![This int node highlighted here](https://user-images.githubusercontent.com/1261388/27986592-dbdae7dc-63b5-11e7-8a98-fb4c02b7ec65.PNG)

If you look in-game this node is definitely counted for the medium threshold. You can tell by the glowing outline as well as the fact there is a cursor tooltip with the jewel summary:

![pob bug report poe](https://user-images.githubusercontent.com/1261388/27986618-0fdb6c46-63b6-11e7-906d-9fb9de953678.PNG)

Thanks so much for your hard work!

**Comment by Openarl** [comment]
Firstly, I should point out that the thresholds for jewels don't require the nodes to be allocated (although they used to), so that jewel would activate in that socket regardless of whether that node was included in the radius (since there are more +10 Intelligence nodes to the right).

Anyway, all of the positions for passive nodes is taken from data provided by GGG, and according to that data, that node is 1201 units away from the socket, and shouldn't be included in the medium radius (which is 1200 units). So I'm not sure why the game is displaying it so; I'll need to look into it some day.

**Comment by chuson** [comment]
I actually never read very closely and thought they had to be allocated!

I'm going to close this as there is definitely enough int in range to not be a problem anyway. I would be interested to find out why there is a difference between the in-game tree and the POB tree though.
