### ISSUE TITLE
"Show node power" should not include nodes from unspeced acendencies.

### ISSUE THREAD

**Issue by rednax825** [Openarl/PathOfBuilding#446]
In the current version, the "show node power" option includes nodes from unspeced acendencies. This is not useful and messes up the node weights.

Ex: Aspect of carnage outweighs all other nodes despite being a ranger.

**Comment by Openarl** [comment]
You are mistaken; nodes that cannot be allocated by the current class/ascendancy are ignored when determining the colour scale for node power, so the most powerful reachable nodes are always shown using the same colours. However, since the colouring method used is able to show power beyond the maximum from reachable nodes, then unreachable nodes can be shown as more powerful than reachable ones (which is intentional).
