### ISSUE TITLE
Where am I getting instant leech from?

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#459]
I've been looking for a while, but I don't know where I'm getting the instant leech from. I have no Vall Pact, no Acuity, no Legacy Vinktars: https://pastebin.com/f51ppRw1

**Comment by Openarl** [comment]
The program cannot calculate the hit rate for spells triggered by CoC yet, so they are displayed in Average Damage mode. Since the hit rate is required to calculate your leech rate, when in Average Damage mode the program instead shows the average life leeched from each hit. In your case that number is quite big, so you'd presumably be at your leech cap (1218 per second) at all times, but the program can't know that.
