### ISSUE TITLE
Incorrect static attack speed and DPS calculations on this build

### ISSUE THREAD

**Issue by joethegitter** [Openarl/PathOfBuilding#472]
To repro:
 - Import 2.6 build from user SonOfSmak, character "HulkingShoulders"
 - Note attack rate of "Cyclone" skill: 4.57
 - Use "Skills" to disable every skill but Cyclone - this should be like standing in town;
      - note attack rate: 3.86, 
      - note DPS: 30,645.4
 
Result: 
 - standing in town, in game, POE shows "attack rate" for cyclone to be 3.88
 - game shows DPS as 31,777.2

More:
 - in PoB, use "Skills" to turn all of the other skills back on
 - use "Configuration" to turn on "Endurance Charges", "Fortify", "Have you killed recently?"
 - note attack rate: 4.82
 - note DPS: 53,343.8

Result:
 - in game, with all 7 endurance charges going, Herald of Ash going, Fortify going, Vitality going, having just killed many enemies, standing next to my totem, 
 - game shows attack rate: 4.83
 - game shows DPS: 49,700.1

So there are two issues, which may be related: your initial calculation of Attack Rate is too slow, and your final calculation of DPS is way too high. I can't think of what I might be missing in game, or what I need to be turning off in PoB to get a more accurate reading?

**Comment by joethegitter** [comment]
Sorry, should have mentioned: PoB build 1.4.50, PoE build 2.6.3, 64 bit client

**Comment by joethegitter** [comment]
Bandits = Passive, Passive, Passive in both cases (PoB, PoE)

**Comment by Openarl** [comment]
Firstly, it's quite normal for the Attack Rate or DPS to be slightly off due to rounding errors, but the difference is usually in the order of 0.5%, and the calculations for Attack Rate are well within that margin.

The differences in Total DPS however are much larger, and are due to two things:
1. There's an additional condition that you need to enable: "Are you always on Full Life?", for the 60% increased Melee Damage from Daresso's Salute
2. The program doesn't automatically disable the gems in your Body Armour while you're using The Bringer of Rain, and the Ancestral Warchief that's in your Tabula is causing most of the discrepancy, so you need to keep that Socket Group disabled

With those corrected, the program reports an unbuffed DPS of 31854.8 (off by 0.2%) and an in-combat DPS of 49967.0 (off by 0.5%).

**Comment by joethegitter** [comment]
Sounds reasonable. I had a suspicion that it was specific to this build, as none of my other builds was showing this level of discrepancy. Thanks for the explanation!
