### ISSUE TITLE
Arcane surge not applying depending on weapon hand when dual wielding

### ISSUE THREAD

**Issue by tgavankar** [Openarl/PathOfBuilding#478]
I made this build and noticed that I only get the arcane surge buff if I have The Scourge in Weapon 1 and Cybil's Paw in Weapon 2. If I swap them (i.e. put the Cybil in Weapon 1 and Scourge in Weapon 2), the Arcane Surge buff is not applied. Arcane surge is linked to Whirling Blades and marked as in Weapon 1.

No arcane surge (Cybil in weap1): https://pastebin.com/RRdCcN3t

Arcane surge (Scourge in weap1): https://pastebin.com/4uRSPeen

**Comment by tgavankar** [comment]
This is in v1.4.51.

**Comment by Openarl** [comment]
Arcane Surge can't be triggered by attacks, so it isn't being applied by Whirling Blades at all. The reason it's applying when The Scourge is in Weapon 1 is that The Scourge grants a skill, Summon Spectral Wolf, which is a spell, and can be supported by Arcane Surge, although since it is triggered it can't actually apply the buff. Ideally, the program would disable the buff when linked to such spells, but that's rather difficult to do.
