### ISSUE TITLE
[Feature Request] Some Spectre info

### ISSUE THREAD

**Issue by hsjing** [Openarl/PathOfBuilding#492]
I know it's probably low on the priority list, but the viable spectres list hasn't been updated in a while.

With 3.0 rolling out, a lot of new spectres are viable.

A lot of people have been using Kitava's Herald and Bone Husk as their primary spectres, so even a preliminary addition would help out a lot.

**Comment by Openarl** [comment]
Unfortunately I'm having some difficulty exporting minion/monster skills from 3.0, as there's a new scaling mechanism employed. I need to get that fixed before I can add any 3.0 spectres; I may be able to get it done before 3.0 is out, but I can't guarantee it.

**Comment by livejamie** [comment]
This would be a huge lifesaver if you were able to get around to it, thank you.

I've gone ahead and subscribed your Patreon.

**Comment by krab** [comment]
Wicker Man and Solar Guard pls 👍

**Comment by darkdex52** [comment]
The new Spectres need to be added.

**Comment by mluckeystrauss** [comment]
second the need for an update of the spectre library :) any news about the problem? and as a side question which you may perhaps know more about than myself: is it possible that poedb.tw is wrong about monster skill damage in general? they show flat damage values for monster skills with no info about level scaling...

**Comment by timneve** [comment]
Really looking forward to getting the 3.0 spectres in Path of Building, this could be so crucial in coming up with new interresting spectre playstyles.

**Comment by JoeTheFkingFrypan** [comment]
I would be eager to participate in the development of that feature.
I managed to find the metadata associated to solar guards. What more is required to add them to the list?

**Comment by Openarl** [comment]
I can already export the basic stats of the new spectres (life, resists, base weapon damage, etc); the problem lies with their skills. 

As I've mentioned before, 3.0 changed the way monster skills scale with level. Previously, most monster and minion skills (particularly spells) had multiple levels, with the monster using the highest level for which they met the level requirement. In 3.0 however, a continuous scaling system was introduced which determines the stat values for a monster's skills based on its level, as well as various parameters specific to the skill.

The difficultly I've had is working out exactly how that scaling works. I've studied it long enough to figure out what all of the scaling parameters do, and how they factor into the calculations, with the exception of one: in the GrantedEffects table it is the one currently labelled as "Multiplier2" by PyPoE. I know that it controls the scaling of the base effectiveness value, which is then multiplied by Multiplier1, then the StatXFloat and EffectivenessCostConstant that correspond to the output stat; but the formula for that scaling has thus far eluded me. I suspect it is some sort of complex exponential formula, but how that formula is structured and the manner in which its parameters relate into Multiplier2 is a mystery.

While this issue only really affects spells (since monster attacks generally only have one level), unfortunately the most desirable spectres are invariably spell-based, so until that scaling is worked out I can't add any of them.

**Comment by emartinezgh** [comment]
On the spell scaling issue, is there any way in which we could help figuring out the formula or even collect data for a brute force approach of having a lookup table for values for each level?

If we take the multi level data as it existed before 3.0, could we at least come up with an approximated formula from that? If they changed from tabular data to a formula I would guess that the scaling formula is what the tabular data was based on originally unless they did revamp all of it. It would be a huge effort to revamp it all.

Hope we can help you crunch numbers and curve fit to find some sort of approximation.  Of course we would need to be provided with some data to work on.

With the upcoming patch this week we could grab a ton of data points if it is possible and legal to memory read them as we will be able to down level or up level our spectres at will. Having a table lookup might be an option until the formulas are figured out.

**Comment by hgfedcba** [comment]
bump

**Comment by Kagerfef** [comment]
Has there been any progress with finding/entering Spectre data?  Hard to assess my Kitava's Herald output without investing a few hours leveling/buying gems in game.

I've been keeping Patreon running for this project since I play Path of Building at work more then I have time to play actual Path of Exile :/

If we are still stuck trying to extrapolate spectre data then I fully understand.

**Comment by xSirk** [comment]
I'm using Cannibal Fire-Eater spectres. When I use Fire Pen (and "is the enemy Ignited?" checked) on my 6L set-up it doesn't change DPS, is this going to be fix when the Spectre Library gets updated?
my build-> https://pastebin.com/0b3bfCwW

**Comment by psouza4** [comment]
I don't want to be that "how about now?" guy, but certainly would appreciate even a rough ballpark even if the DPS can't be guaranteed.

**Comment by Openarl** [comment]
Time for a long-awaited update!

Mark has given me the necessary information to implement the new monster skill scaling system; I'm working on it now, so hopefully you'll see some new spectres coming within the next week (time-permitting).

**Comment by mluckeystrauss** [comment]
Holy Shit that are great News! Did he tell you why he suddenly shared it
with you? Looking forward to those spectres :-)

Openarl <notifications@github.com> schrieb am Mi., 24. Okt. 2018, 14:38:

**Comment by Openarl** [comment]
I actually went to him for the information.

**Comment by Kagerfef** [comment]
GGG is amazing transparent as a dev company.  Really excited to see this when it's working!

**Comment by livejamie** [comment]
Will this include other minions that we don't have like Herald of Agony?

**Comment by Openarl** [comment]
I will now be able to do damage calculations for all monsters and minions in the game, so yes, that includes HoA.

**Comment by Openarl** [comment]
It now gives me astounding pleasure to finally close the hell out of this issue!

**Comment by Exportforce** [comment]
Sadly...
![image](https://user-images.githubusercontent.com/627469/47557053-1502a880-d910-11e8-88b8-9e8057c4933e.png)
Happening on this Build: https://pastebin.com/GJjjqPSk
