### ISSUE TITLE
Add 'Is Enemey on Full Life?' for Assassin class on Ascendant

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#53]
It doesn't calculate the 40% multiplier on enemy full on life.

Also why some of the mod rolls are in red and not blue when hover over nodes?

**Comment by rhazor** [comment]
Also Gladiator's Painforged doesn't calculate the +block if you were hit recently with the setting ticked under config.

**Comment by Openarl** [comment]
A modifier is displayed in red if the program doesn't support it.

I'll add support for these in the next update. I'll do the Assassinate modifiers too. There'll be 2 new conditions in the Configuration tab for enemy-on-full-life and enemy-on-low-life.

The wording on Painforged is different from the usual "hit recently" condition, which makes me suspect it works differently. I'll tie it to the "hit recently" condition though, since there's little point adding another condition.
