### ISSUE TITLE
[BUG] Stuck with errors while loading old build

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#54]
As title says, I was trying to load [some of my old builds (created on September 2, so I guess it was version 1.0.22 or even below)](https://github.com/Openarl/PathOfBuilding/files/620462/2.3-Champion-Poison-LA.Frostwall.zip) and got stuck with errors. Enter / Escape / F5 did not help, same as app restart.
![first error](http://i.imgur.com/9SPPqZA.png)
![second error](http://i.imgur.com/ySvQF5f.png)

Only after removing 'Mode' node in Settings.xml I was finally able to successfully launch PoB and work with it.
Looks like there need to be some file/format converting and/or failover on app start.

**Comment by Openarl** [comment]
This will be fixed in the next update.

There are actually several conversions present for older variations of the build file format; and in fact it's one such conversion that's triggering this error. It looks like any build saved before 1.0.27 will cause this error when loaded in 1.1.0 or later if there's an empty socket group in the build. The next update will fix the conversion code so that such builds will load properly. If you'd like to load the build before I get the update out, you can edit the XML file and remove any "Skill" elements that have no "Gem" elements in them.
