### ISSUE TITLE
Incorrect calculation on poison on first selection

### ISSUE THREAD

**Issue by twothe** [Openarl/PathOfBuilding#558]
I noticed an issue with my Flicker build when I considered opting into poison on hit. When I had 0% chance to poison on hit, hovering over any passive node that would give 10% poison on hit incorrectly told me, that selecting this skill would add a total poison dps to my current dps equal to my current dps plus the poison damage from the skill (~110% dps gain from a single node). 

After selecting that node it showed the correct amount of dps by poison lost when unlearning that node and no longer showed the excessive amount. 

This issue was 100% repeatable.

**Comment by Yajirushi** [comment]
Whats happening is that the Total DPS inc. Poison isn't populated with the base Total DPS stat before you have any chance to poison, so it shows the total gain from an newly allocated zero dps to the Total DPS plus poison dps.

**Comment by Openarl** [comment]
Yajirushi is correct; the Total DPS inc. Poison stat isn't calculated at all unless you have some Poison, so there's nothing to compare with. I suppose that is a little deceptive, though; I'll change it so that it is always calculated, but only shows up in the sidebar if it differs from the Total DPS.
