### ISSUE TITLE
Equipping and unequipping the same pair of gloves leaves different damage calculation before and after?

### ISSUE THREAD

**Issue by bmer** [Openarl/PathOfBuilding#575]
The build causing the issue: https://pastebin.com/6wvhAxrZ

Unequip the Maligaro's Virtuosity gloves (select None in slot). Re-equip them. Notice how Average Damage and DPS change. DPS jumps from ~16k to ~50k! What's going on?

**Comment by dein0s** [comment]
Everything is fine for me: 49k dps w/o gloves, and 57k w/.
![no_gloves](https://i.imgur.com/n4Vax4O.png)
![yes_gloves](https://i.imgur.com/yOWrrLn.png)

**Comment by dein0s** [comment]
But, I can definetly see another strange thing here:
1) import build
2) set 'flicker strike' as main skill
3) switch to items tab
4) take off gloves
5) main skill changed to 'leap slam' for no reason

**Comment by bmer** [comment]
Hmm. Why do you not see the 16k DPS that I see? 

![image](https://user-images.githubusercontent.com/4350451/29444217-9ea816a8-8392-11e7-9cc7-52c4d4ca900c.png)

Is it because my Main Skill is set wrong?

**Comment by dein0s** [comment]
Erm... Why do you use Lab enchant [Decree of Spite](https://pathofexile.gamepedia.com/Of_Spite) as the main skill at all?

**Comment by bmer** [comment]
How do I set the main skill? I don't think I set it as the main skill.

**Comment by N1gh7h4wk** [comment]
![grafik](https://user-images.githubusercontent.com/22776166/29486502-591fa2e4-84e7-11e7-97cb-04193601c4d7.png)

**Comment by Openarl** [comment]
The main skill is changing because un-equipping the gloves also removes the Decree of Spite skill, and since it is above Flicker Strike in the Socket Group list it causes the main Socket Group to change to the next one in the list, which is Leap Slam. Re-equipping the gloves adds Decree of Spite at the end of the Socket Group list, so the main skill stays the same.

**Comment by dein0s** [comment]
@Openarl how about this https://github.com/Openarl/PathOfBuilding/issues/575#issuecomment-323253189 ?

**Comment by Openarl** [comment]
Err... did I not just explain that in my last comment?

**Comment by Openarl** [comment]
But that's exactly what I was talking about. Removing the gloves also removes the Decree of Spite skill (and the socket group containing it), which causes the socket group list to go from:
1. Decree of Spite
2. Flicker Strike
3. Leap Slam

To:
1. Flicker Strike
2. Leap Slam

And since the main socket group is set by index (to socket group 2 in this case), the main socket group changes from the Flicker Strike group to the Leap Slam group. Granted, it is a little counter-intuitive, but it would be rarely encountered, and probably not worth the trouble to fix.
