### ISSUE TITLE
Total DPS including poison

### ISSUE THREAD

**Issue by kelthalas** [Openarl/PathOfBuilding#58]
Hello

Unless I am mistaken, total dps including poison stacks isn't displayed anywhere. 
It should be as simple as Total DPS + (Poison Chance * Total Damage per Poison * Attack Rate). 
Being able to see how much each node effect this total value would be pretty handy.

Awesome tool, I'm definitely switching from poeskilltree + excel =D

Thanks

**Comment by kelthalas** [comment]
Turns out it's already calculated, just not displayed.
Build.lua:241 I added
{ mod = "CombinedDPS", label = "Combined DPS", fmt = ".1f", compPercent = true },

**Comment by Openarl** [comment]
Firstly, I'm impressed you managed to figure out how to display it yourself!

However, there's a reason the combined DPS isn't displayed. While it is accurate if the only secondary DoT is poison, if you have bleed or ignite then the calculation can't account for them properly. Since they don't stack, unless your bleed/ignite chance is 100% there's no easy way of estimating the likelihood of any given enemy being bled/ignited.

I'd like to find a solution to that problem eventually though; it'd probably involve adding options to allow the user to tell the program how it should factor in each DoT.

**Comment by Openarl** [comment]
There's now a Total Damage/DPS number that includes poison, but not other DoTs.
