### ISSUE TITLE
Unwavering Stance from Kaom's Roots

### ISSUE THREAD

**Issue by stevenolsen** [Openarl/PathOfBuilding#594]
Under **Other Defences**, if I hover over **Stun Avoidance Chance** it reports 100% from **Unwavering Stance** and shows me an unselected node in the tree. My Unwavering Stance is from Kaom's Roots, _not_ from the keystone. As a new player, this was somewhat confusing.

**Comment by Openarl** [comment]
This is a fundamental limitation of the way in which keystones work, both in-game and in Path of Building. 

When you allocate a keystone, or equip an item that grants the keystone, it doesn't actually give you the keystone's modifiers (e.g 100% stun avoidance) directly, but rather it just sets a flag that says "You have X Keystone"; then at a later point the keystone flags are checked and the appropriate modifiers granted to your character. This is necessary to prevent you from gaining the keystone modifiers multiple times if you have multiple sources for the keystone (say, taking Unwavering Stance _and_ equipping Kaom's Roots).

One side effect of this in Path of Building is that when a keystone's modifiers are being added, they cannot have their source set to the source of the keystone flag, as the code only knows that the flag for that keystone has been set, but not _where_ it was set from. So it defaults to the keystone node (as it has to set _a_ source, even if it may not be the true source).

Fixing it would require me to rework the keystone system to allow the source of the keystone flag to be preserved, and given how minor this issue is, I really don't see it being worth the effort.
