### ISSUE TITLE
[BUG] Drillneck Penetrating Arrow Quiver

### ISSUE THREAD

**Issue by 88Stach** [Openarl/PathOfBuilding#60]
There is a bug with "Drillneck Penetrating Arrow Quiver".

Description says _"Projectile Damage increased by Arrow **Pierce Chance**"._
Unfortunately it is not working.
You can add remove nodes in **pierce chance** while having that quiver and it isn't increasing projectile damage (DPS / average hit / ect) by **pierce chance**

**Comment by Openarl** [comment]
I can't reproduce this. I have a build with Drillneck and the projectile damage increase is definitely applying.

Are you aware that pierce chance cannot exceed 100%, and therefore the Drillneck bonus also cannot exceed 100%? If your pierce chance is already 100% (if, for example, the skill has an inherit 100% pierce chance) then adding pierce chance nodes won't change your damage.

**Comment by 88Stach** [comment]
K... i found that "Deadeye" perk "Powerful precision" which grant 100% chance projectile piercing at the start, and counting it too (which should not (game doesn't))

**Comment by Openarl** [comment]
Oh, that'd do it. I actually forgot I'd implemented that passive in that way... I'll change it so that the extra pierce chance only applies in Effective DPS mode, so that the DPS and pierce chance will match the in-game tooltip when in other modes. I might reduce the pierce chance too, perhaps to 50%? 100% is definitely unrealistic.

The better option though, would be to add a "distance to enemy" option in the Config tab, so it can scale it accordingly. That'd also allow Point Blank and Far Shot to work properly. That's a task for another time though...

**Comment by Openarl** [comment]
Powerful Precision will be properly supported as of next update, with a "Projectile travel distance" option.
