### ISSUE TITLE
Jewel affixes incomplete+incorrect ranges

### ISSUE THREAD

**Issue by mrmonday56** [Openarl/PathOfBuilding#61]
eg melee crit multi is max 10 instead of 12-15 and weapon specific affixes are mia

http://poedb.tw/us/mod.php?cn=Jewel&an=strjewel

**Comment by Openarl** [comment]
The crit multi ranges will be fixed in the next update. It seems the affix list I was looking at is out of date.

As for the missing affixes, that's intentional. The jewel templates (and indeed all rare templates) aren't meant to be 100% complete; they're there just to allow a close approximation of a build's gear. Having to use, for example, "%increased Physical Damage with Two Handed Melee Weapons" instead of "%increased Physical Damage with Maces" isn't going to make a meaningful difference in the calculations.

**Comment by mrmonday56** [comment]
Yes but the weapon specific ones have higher ranges

**Comment by Openarl** [comment]
They do, but the top end is only 2% higher. The differences that will exist between your theoretical gear, and the gear you'll actually end up using, will make a much bigger difference than an extra 2% increased damage, so I see little point worrying about it. Regardless, if you really need those specific affixes, you can add them yourself using the item editor.

**Comment by myrahz** [comment]
Just a help for the stat list:

poeaffix.net

I suppose it goes into Data/Rares.lua ?

**Comment by Openarl** [comment]
That it indeed the place. I already know about poeaffix.net and such, I just don't see the point in adding every single possible modifier to the templates.

**Comment by Openarl** [comment]
The next update will add a new crafting system for jewels (and flasks, which are being added); this system will include all possible modifiers for those items, which solves this issue entirely.

**Comment by myrahz** [comment]
Wow nice, any ETA?

**Comment by Openarl** [comment]
The update should be out in a day or two; there's still some work to be done but it's mostly ready.
