### ISSUE TITLE
Wither Stacks

### ISSUE THREAD

**Issue by eskalimur** [Openarl/PathOfBuilding#615]
Please make and Option for 0 Wither Stacks, if I want to calculate my Damage without using SpellTotemWither on Thrash its always one Wither Stacks unless is disable skill, and 0 makes much more sense than 1.

And Blade Vortex should be the other way, makes no sense to calculate Damage for 0 Blades, you will never deal damage with 0 Blades, always 1 or 2 atleast.

Thanks

**Comment by Openarl** [comment]
If you want to disable a skill, use the disable option in the Skills tab. It is a specific design choice that I made that any skill that is enabled should be doing _something_, even if the program doesn't yet have all the information necessary to determine exactly what it should be doing (so in this case, knowing the stack count from the user input).

As for Blade Vortex, the 0 blades option exists because it allows you to compare the DPS numbers with the in-game character sheet while no blades are active. Indeed there are many options like that which have no relevance to real-world DPS (such as the 1 Stage option for Flameblast), but which are merely there for the sake of comparison.

**Comment by eskalimur** [comment]
well I disagree as user, since nobody needs to know damage of one with stacks and it makes the program just way less satisfying to use.

Like nearly everybody I ever saw doing poison build disables it or puts it on 5+ Stacks.

**Comment by Openarl** [comment]
You are correct in that no-one would actually use the 1 Stack option, but the program must rely on the user to set the correct stack count, and until that occurs it obviously needs a default option, and 0 Stacks is not an acceptable default for the reason I listed earlier.
