### ISSUE TITLE
"Max Poison Stacks" should be named "Average Poison Stacks"

### ISSUE THREAD

**Issue by hgfedcba** [Openarl/PathOfBuilding#641]
The above mentioned stat shows how many stacks of poison a permanently attacked enemy has on average, as it includes the chance to poison. The real "Max Poison Stacks" would assume that every hit that can poison does so and rounds that value up, which doesn't help at all, so you should just rename it.

**Comment by Openarl** [comment]
Assuming every hit can poison would indeed be useless, which is why "Max Poison Stacks" isn't intended to mean that. 

There are a few mechanics in the game that interact with the poison count on the enemy, such as Growing Agony. However, although the program can calculate the average number of poisons on the enemy, for various reasons it does not automatically factor that into the calculations for such mechanics. The "Max Poison Stacks" output was added primarily to inform the user of the number of poison stacks that would be on the enemy while attacking it constantly, so that the user can input a reasonable stack count (perhaps half that amount) into the "# of Poisons on Enemy" option. 

So in that context, "Max" doesn't mean "maximum if you had 100% poison chance", but "maximum if you attacked non-stop", as opposed to what you're likely to sustain in a real encounter where movement is required. So I think the current wording is fine.

**Comment by hgfedcba** [comment]
What you are saying makes a lot of sense, but only if you use the word "average" instead of "max". The user indeed wants to know how many stacks of poison there are on **average** if you attack an enemy non stop and that could be a number like 2.1.
The user is not intersted in the

> "maximum if you attacked non-stop"

, which you would get by assuming every hit applies posion and then rounding up.

Even if you don't agree with that, one can conclude by siple logic, that 2.1 can't be the "maximum if you attacked non-stop", as the maximum has to be a natural number for Example:
If you have 2 stacks 9 out of 10 times and 3 stacks else then the maximum would be 3. What you show is 2.1 and that is the (arithmetic) average.
(I am a mathematican and maybe a bit pedantic here as that is not one of the most important problems, but I do feel it is wrong)


On another note: It would be nice to have and option to dynamically adjust the "# of Poisons on Enemy" in relation to the "Average Poison Stacks" modifier. You can maybe click a box an then the # of Poisons number is automatically set to be half of "Posions Stacks" number.
That way you don't have to manually update every time you make changes to poison chance or attack speed.

**Comment by hgfedcba** [comment]
Hi
I wrote a reply to you closing the case as I disagree, but the case 
isn't opened automatically. If it isn't opened in the next week or I get 
another reply I will open another case with the same content.

Am 23.09.2017 um 14:02 schrieb Openarl:

**Comment by Openarl** [comment]
It is perfectly true that the "Max Poison Stacks" output is mathematically an average. But that isn't what the "Max" is meant to imply; it means "this is the average number of stacks that you will sustain under ideal conditions", and the actual average that you will sustain in combat will typically be lower; in other words, that output is the upper limit ("maximum") of what you can sustain. And if the quick survey I conducted is any indication, then that is how users normally interpret it.

Anyway, the breakdown for the Max Poison Stacks makes it quite clear that the poison chance (if less than 100%) is factored in, so I don't think there's much room for confusion.

Regarding the dynamic adjustment, there are technical reasons why the program doesn't do that at the moment. The program does the damage calculations in a single pass; in order to calculate how many poison stacks the enemy will have, the program needs to perform the poison base damage calculations, but that can depend on knowing the number of poison stacks on the enemy, thus creating a circular dependency. This cannot be fully resolved without changing the DPS calculation system to use combat simulation, as there are many nasty edge cases involved.
