### ISSUE TITLE
Life/Mana leech not being taken into consideration when using Taproot

### ISSUE THREAD

**Issue by Wires77** [Openarl/PathOfBuilding#642]
Taproot leeches life from maimed enemies and mana from poisoned enemies with attack damage.  This leech does not show up in calculations even when enemy is maimed in the configuration.

Here is the build I was playing around with when I discovered the issue:  https://pastebin.com/8YFpGZ2h

**Comment by Openarl** [comment]
The "against Maimed Enemies" qualifier isn't currently recognised by the program, but that will be fixed in the next update.

However, even with that fixed, neither the Life nor Mana Leech from Taproot will have any effect on your build, as you already have enough Leech from other sources to hit the maximum Leech rates for both Life and Mana.
