### ISSUE TITLE
Freezing Pulse shows wrong Avarage DPS

### ISSUE THREAD

**Issue by yiyaboga** [Openarl/PathOfBuilding#659]
Hey there,

 I'm playing with an Inquisitor right now, when I import my character into PoB I've noticed that Freezing Pulse Avarage DPS was showing wrong (I guess base values of Freezing Pulse is wrong) for simplified as much as possible I unequipped everything and I only have lvl:19 q:20 Freezing Pulse with that setup PoB shows Avarage DPS: 9.138,1 meanwhile in game DPS is 13.316,7 I've checked Cast Rate, Crit Chance and Crit Multiplier is correct. I'm also adding some in game screenshots and PoB pastebin ;

> PoB pastebin: https://pastebin.com/1P3Z39DU

> In-game SS : https://imgur.com/a/TDUCo

**Comment by Openarl** [comment]
Firstly, you're looking at the wrong output for the DPS. "9,131.8" is the "Average Hit"; you need to look at "Total DPS", which is further down. 

However, in this case the Total DPS is 18,825.6, which is higher than the in-game tooltip; that's because Path of Building's DPS calculation takes into account many factors that the in-game tooltip does not, and is therefore more accurate.

In this case, the Penetration from Celestial Judgement and Inevitable Judgement, as well as the "Nearby Enemies Take 16% increased Elemental Damage" from Augury of Penitence, are both affecting your DPS. Additionally, the "30% increased Spell Damage if you've Cast a Spell Recently" from Instruments of Virtue is also applying, as it would always be active in combat (since your main skill is a spell).

If you want to compare the program's output with the in-game tooltip, you can go to the Calcs tab and change the Calculation Mode at the top left, which will affect the output shown in the Calcs tab. In this case, changing it to "Unbuffed" or "Buffed" will disable those extra effects, which brings the DPS number to within 0.05% of that shown in-game.
