### ISSUE TITLE
[Bug] UI is improperly sized and misaligned when first opening program

### ISSUE THREAD

**Issue by Kubius** [Openarl/PathOfBuilding#677]
This has been a consistent issue for a few revisions now. The "view area" will be a subset of the actual window, and my mouse doesn't line up with the UI. Here's a picture of PoB open, with my mouse over "Flurrytest" and the program incorrectly highlighting "inquis kitava's thing wip":

![pobissue](https://user-images.githubusercontent.com/12454065/31967861-cfd45512-b8d4-11e7-8237-5af847e8d538.png)

Refreshing the window in any manner, including minimizing and restoring it, returns the program to normal. OS is Windows 7 x64, with Radeon 17.4.3 GPU drivers on an RX 470.

**Comment by Donlod** [comment]
Since 1.4.64 im also experiencing this when starting the program.

[image](https://i.imgur.com/iECKtFL.jpg)

It also looks like the UI and the interaction with the elements do not match. When hovering over "<< Back" im actually selecting the main skill drop down.

If i resize the window then everything is fine again until restart.

If i do not resize the window and just restart the program it will load correctly without this bug, but the window will also be reset at its default dimensions.
If i change the size of the window (e.g. make it bigger again) and then restart the program its again messed up like in the image linked above.

So im left with two alternatives.
1) just use the default window dimensions or maximized mode.
2) if i do not want it to be like in 1) i have to resize it everytime i start the program.

**Comment by Openarl** [comment]
Sorry for the delay in addressing this; I've been extremely busy as of late.

This is fixed in the next update.
