### ISSUE TITLE
Life calculation

### ISSUE THREAD

**Issue by edxp** [Openarl/PathOfBuilding#705]
Total life value differs from the one in game after importing character. Can't seem to find what is causing the difference.

PoB version: 1.4.64
You can try it yourself:
Login: willnotsustain
Character: Buerno

Pastebin: https://pastebin.com/PknX8agv
Screen shot from game: https://i.imgur.com/2LOtt3G.png (7256 total life)
Screenshot from PoB: https://i.imgur.com/9n21WgF.png (6939 total life)

If there is any additional information required for localizing the issue, please let me know.

**Comment by eps1lon** [comment]
The Pariah mod `+100 maximum life per red socket` is currently not supported. 

Mods on items or tree that have a red color are currently not supported. PoB only supports calculations for mods with green colors.

Since this issue is submitted quite often (#428, #304, #207, #107) it might be time to think of a better way of displaying unsupported mods. A striket hrough the text might be better suited. Red/green are already used for changes in calculated values. Little <sup>tooltip note</sup> might also help.

**Comment by edxp** [comment]
I don't know why I didn't think about it.
Maybe it'd be a good idea to treat Pariah as Variant unique depending on socket colour.

Thanks for the heads up.

**Comment by eps1lon** [comment]
Socket color isn't supported at the moment (see #353). You could just manually add a line by editing the item that just adds +100 life.

**Comment by Openarl** [comment]
Duplicates #353, as per @eps1lon's comment.
