### ISSUE TITLE
[Very minor] Still says 3.0 Fall of Oriath when going trough what skill tree version

### ISSUE THREAD

**Issue by dybdaltech** [Openarl/PathOfBuilding#712]
https://i.imgur.com/VvqfN6h.png

**Comment by Openarl** [comment]
This is intentional. The game version labels aren't intended to reflect the exact versions of the data used (otherwise it'd say 2.6.3 instead of 2.6), but rather serve to distinguish the... eras? of the game that the options represent. The changes with 3.1 weren't significant enough to justify adding a 3rd option, so 3.1 will fall under the "3.0" era.
