### ISSUE TITLE
Molten strike does not benefit from multistrike

### ISSUE THREAD

**Issue by roparex** [Openarl/PathOfBuilding#718]
https://pastebin.com/yneQkBp9
With this build, i had 6.8 attacks per second before the patch. Now i only have 3.7. It is because multistrike no longer works. If i remove it i have the same attack speed but 60% more dps (on molten strike balls).

**Comment by roparex** [comment]
Melee still benefits, however balls should have the same attack speed, shouldn't they? Even without multistrike, melee hit has 3.84 attack speed and balls have 3.78, so there might be more issues with the balls interaction.

**Comment by Openarl** [comment]
The calculation for the attack speed of projectile parts of melee skills (such as Molten Strike's Magma Balls or Lightning Strike's Projectiles) has never been accurate, due to a limitation of the program's skill part system; the fix to Multistrike merely made it more obvious. I've previously detailed this in #241.

Fixing this is a higher priority now due to the greater impact, but I suspect that it will require a rework of the program's skill part system, and I'm not sure when I'll find the time to do that.

Anyway, this duplicates #241, so I will close this.
