### ISSUE TITLE
[Bug] Toxic Delivery and Noxious Strike not working

### ISSUE THREAD

**Issue by zocke1r** [Openarl/PathOfBuilding#72]
The more multiplier from Toxic Delivery does not seem to be included in in the Calculation for Poison . I assume the reason for this is that its a conditional modifier that only applies ifyou crit, so unless my brain is failing me atm the average more Multiplier should be your crit chance * chance to hit* chance of application (which is 1) so just the crit chance * chance to hit.

In a similar fashion it should be possible to calculate the chance of applying poison against Bleeding Enemies (Noxious Strike), as that should be the chance of an enemy bleeding * chance of inflicting Poison against bleeding enemy, 
This is of course only true for the first two hit, but for increasing number of hits the chance would increase as such this should be the lower bound value and as such would be significantly more useful for planning as opposed to simply ignoring the stat in its entirety. And for enemies that get one shot all  dmg calculations are useless anyways

**Comment by Tripwyr** [comment]
It actually is factored, but it is factored in under Crit Effect Mod instead of Total More. If you mouse over Poison DPS on the Calcs page, you will see on the third line: "+(crit chance x crit multiplier x 2)" if you have Toxic Delivery, but only "+(crit chance x crit multiplier)" without Toxic Delivery.

**Comment by zocke1r** [comment]
actually without toxic deliver it does not even display that block in its entirety and i have to say it is quite well hidden

**Comment by Openarl** [comment]
Unfortunately the only way to accurately simulate Toxic Delivery is by recalculating the crit effect modifier (and yes, I've done the math to prove it). That's because the damage increase scales with both critical strike chance and crit multiplier. I know it's not intuitive, but I can't do much about that. You just have to trust that the program is calculating it correctly...

Regarding the poison chance against Bleeding Enemies, the program will take that into account if you set the "Is the enemy Bleeding?" option in the configuration tab. It doesn't try to guess whether an enemy will be bleeding or not.
