### ISSUE TITLE
Molten Strike - Magma Balls' dps not being affected by "melee attack speed" stat

### ISSUE THREAD

**Issue by bdg0** [Openarl/PathOfBuilding#725]
Pretty self-explanatory issue. The dps calculation in previous versions included the "melee attack speed" stat, and live version's calculation doesn't.

**Comment by Openarl** [comment]
As explained in #718 and #241, the attack speed calculation for Magma Balls and other projectile parts of melee skills has never been accurate, due to limitations of the program's skill part system. The change to Multistrike's behaviour was intentional by the way, although I didn't realise that it would make these calculations even less accurate.

I do see this as a problem though; I may revert the Multistrike change, but I'd rather that users don't rely on the attack speed calculations for those parts at all. The ideal solution involves reworking the skill part system to make the attack speed calculation accurate in cases like this, but I suspect it will take a fair bit of work. Either way, finding a solution is a priority.
