### ISSUE TITLE
Point Blank not functioning

### ISSUE THREAD

**Issue by Tripwyr** [Openarl/PathOfBuilding#73]
Point Blank does not seem to function. Having Close Range checked works with Chin Sol, but not the Point Blank keystone or the Point Blank support gem (0-38% increased projectile damage works, 50% more doesn't).

**Comment by Openarl** [comment]
Point Blank and Far Shot can't work without knowing how far away the enemy is. I'm considering adding a field to the Configuration tab that'll allow you to input an estimate of the distance. I'm not too fond of throwing estimates into the damage calculations though; but I may make an exception in this case, since I've had a few requests for it.

**Comment by Tripwyr** [comment]
While I agree that estimates aren't always pleasing, traps get a guaranteed 50% more from Point Blank, so it would be nice if we could somehow represent this.

**Comment by humenbean** [comment]
Really wish it was just assumed you were within the 20 units. I mean, this program is mainly used for most people to find their build in 'ideal' circumstances. Just make it the best case scenario. Or put in an option like wither totem with range attached. I really want to see what my build does DPS wise all specced out, but there's a few things that make it impossible right now, like point blank not calculating at all. I had another question, but I should keep on topic here. I'll head over to the forums! Thanks.

**Comment by Openarl** [comment]
The next update adds a "Projectile travel distance" option, and support for Point Blank.
