### ISSUE TITLE
[BUG] Offhand Sunder

### ISSUE THREAD

**Issue by CommissarMaihem** [Openarl/PathOfBuilding#737]
Sunder in the program doesn't get bonus from the off-hand weapon or using nodes related to the off-hand (like sword nodes) but inside the game I got those bonus to the damage (using Axe+Rapier) putting points in Brutal Blade as example.

**Comment by Openarl** [comment]
In this case it is actually the in-game tooltip that is incorrect. 

Sunder only uses the main hand weapon, so modifiers that only affect the offhand cannot ever affect the skill's DPS. However, the in-game tooltip DPS has never really been accurate when dual wielding due to multiple bugs, mostly relating to the tooltip incorrectly factoring in weapons that the skill does not or cannot use; so it really cannot be trusted.
