### ISSUE TITLE
[Bug] Adder's Touch not working

### ISSUE THREAD

**Issue by zocke1r** [Openarl/PathOfBuilding#74]
The 30% chance to apply poison on crit does not get factored into poison chance

**Comment by Openarl** [comment]
Correct; since it only applies on crit it's not as straightforward to implement as a global poison chance increase. I'll look into it though; I think I know a way I can factor it in without going to too much trouble.

**Comment by zocke1r** [comment]
wouldn't crit chance  * 30% (chance to Poison from adders touch) give you the correct % chance to poison on any given hit ?

**Comment by Openarl** [comment]
Yep, that's how it'll be factored in. It'll be in the next update. I've managed to do it without actually changing the poison chance calculation, which is what I meant by "not going to too much trouble".

Strictly speaking, this passive affects the average poison damage too, since poison will deal more damage on crits, and with this passive, the likelihood of any given poison stack having been applied by a crit is higher than your crit chance would suggest. In the extreme case, where you have no other poison chance, all poison stacks will be applied by crits, so the poison damage calculation will be way off. The thought of trying to factor that in gives me a headache though!

**Comment by aggixx** [comment]
You could calculate the poison chance it grants as a ratio of hit damage vs crit damage. For example if 90% of your damage is dealt by crits then 30% chance to poison on crit would be worth 27% chance to poison.

**Comment by Openarl** [comment]
That _might_ correctly account for it under normal circumstances, but I guarantee Toxic Delivery will make a mess of it. It'll take a more complex approach to correctly simulate this, unfortunately.

**Comment by Openarl** [comment]
The next update changes the handling of crit and dot calculations such that Adder's Touch and other modifiers that grant a chance to bleed/poison on crit can now be handled 100% correctly.
