### ISSUE TITLE
Lightning strike's projectile damage with multistrike is mistaken

### ISSUE THREAD

**Issue by Vash115** [Openarl/PathOfBuilding#758]
As the title says, when you link multistrike to lightning strike, the projectile atts doesnt go up, even tho it directly depends on the melee atts, so it should (the problem is clearly that multistrike is tagged as 'melee' and PoB then ignores it when looking at the projectiles). I belive there are a few other interactions that work incorrectly with lightning strike as well.

Thank you very much, (love your software btw).
Nicolas.

**Comment by Openarl** [comment]
As noted in #241, the attack speed calculation for projectile parts of melee skills has never been correct, due to limitations in the design of the skill part system. However, the recent bug fix to Multistrike has exaggerated the problem somewhat, and overhauling the skill part system to fix the issue is now a high priority. Unfortunately though, the overhaul is likely to take a fair bit of work, and it may be a while before I can get around to it.
