### ISSUE TITLE
Watcher's Eye mod Gain X% of Maximum Mana as Extra Maximum Energy Shield yields wrong ES values

### ISSUE THREAD

**Issue by daish0** [Openarl/PathOfBuilding#759]
The mod appears blue and seems to be supported (works when Clarity is switched on and off), although calculated flat ES value is wrong and doesn't appear in the "Calcs" tab as Base in the "Energy Shield" box.

For example, my character has 1,381 total Mana.
I have a Watcher's Eye with 14% Mana gained as ES.

Without the Mod I have 6,638 ES and when adding 193 flat ES (1381 x 0,14) I get exactly 7,500 total ES (which is correctly done in game), in Path of Building though I get 7,338 ES for whatever reason.

**Comment by Openarl** [comment]
As far as I can tell the modifier appears to be working correctly; I will need a pastebin link of the build, or a character to import.

**Comment by daish0** [comment]
Hi,

here's my PasteBin: https://pastebin.com/vebApWEU

I added the mods of Watcher's Eye to my Quicksilver Flask in Flask Slot 5, as I had to fill one passive Tree Jewel slot with the Jewels from the unique Stygian Belt.

Just add the ! exclamation mark before the flat ES roll on the Quicksilver and remove the one before the Mana as ES mod to enable it.

**Comment by Openarl** [comment]
Well, I'm a little confused now...

The modifier on Watcher's Eye is worded exactly like a conversion (and the program automatically detects and handles it as such), and it should therefore follow the standard conversion calculation process. 

That process works quite differently from the calculation that you came up with (1381 x 0.14); what should actually occur is that the game takes 14% of your _base_ Mana, then applies all modifiers to Mana and Energy Shield simultaneously. And that is how the program is handling it, and it is how other similar stats work (e.g on Hierophant's Sanctuary of Thought).

However, the fact that your calculation matches the in-game result clearly demonstrates that this modifier is *not* functioning as a conversion. But given its wording it absolutely should be, and so I believe that it is actually the *game's* handling of this modifier that is incorrect, not PoB's.

I would suggest raising this issue with GGG; I can't easily create a workaround to simulate the game's behaviour in this case, so either the game's handling of the modifier needs to be fixed, or they need to change the wording so that it doesn't imply conversion.

**Comment by daish0** [comment]
Hi,

I just checked a random guy that play's Hierophant with this Node you mentioned and Mana/ES values of Path of Building and Ingame seem to be correct. So there is a different between this Node calculation and the one from Watcher's Eye.

Will open a thread in the official Forum about it.

**Comment by daish0** [comment]
Bug report here: https://www.pathofexile.com/forum/view-thread/2050823

**Comment by Ruba87** [comment]
Additional Energy Shield = total mana * 0,18 * (1 + total increased ES)
0.18 - 18% (from Watcher's Eye)
