### ISSUE TITLE
Vile Toxins Support donot work with united in dream

### ISSUE THREAD

**Issue by ogurisan** [Openarl/PathOfBuilding#760]
it only add few poison damage to poison dps

**Comment by kotadog** [comment]
I can't tell for sure, but I think I'm having the same problem here with vile toxins is not actually calculating into the damage of the poison for the skill.

Example POB: https://pastebin.com/4bCZCV79  Enable disable on Viper Strike or Lightning Strike.

**Comment by Openarl** [comment]
This is fixed in the next update.

@kotadog:
Your Viper Strike is socketed into The Embalmer, which is granting Vile Toxins, so enabling/disabling the gem itself has no effect (as it is redundant).
As for the Lightning Strike, Vile Toxins is definitely applying correctly. Make sure you're switching your Main Skill to Lightning Strike when checking this, otherwise it won't show any effect.

**Comment by kotadog** [comment]
Thanks for the reply.  I am new to the tool/poe and didn't even see you could select the socket location.  Appreciate the update and sorry for the newbness.
