### ISSUE TITLE
Lightning strike and Multistrike

### ISSUE THREAD

**Issue by Charmeleomander** [Openarl/PathOfBuilding#769]
Lightning strike's projectiles don't get the attack speed increase while supported by Multistrike, while the melee hit portion does.

**Comment by Openarl** [comment]
This is a known issue; it's an unintended side effect of an intentional change to Multistrike, but as I've described in #241 the attack speed calculations for projectile parts of Melee skills weren't accurate in the first place, and shouldn't be relied upon. 

Fixing the underlying issue is a priority, but unfortunately it will require a fair bit of work, as the program's skill part system needs to be completely overhauled. I'm hoping to get to it sometime in the next few weeks, though.
