### ISSUE TITLE
Oni-Goroshi has six sockets, but you can only change the first three.

### ISSUE THREAD

**Issue by master2080** [Openarl/PathOfBuilding#774]

**Comment by Openarl** [comment]
Not exactly missed; the item's base, Charan's Sword, is limited to 3 sockets (hence the 3 socket edit limit), but it has a hidden modifier that allows it to have 6 linked sockets. But, the program can't ever see that modifier (because, well, it's hidden!), so it has no way of knowing that it can have 6 sockets.

I think I've found a fairly elegant way to permit an override in this case though, so this should be fixed in the next update.

**Comment by master2080** [comment]
Great!
