### ISSUE TITLE
Perandus Signet not calculating the Intelligence bonus right

### ISSUE THREAD

**Issue by xxFxDx** [Openarl/PathOfBuilding#806]
Example in this build:
https://pastebin.com/JKcQ1J3D

Ingame there is ~1500 Intelligence, while in Path of Building there is only 1156.
Equipping and unequipping the rings (which should affect the intelligence) does not change the stat, therefore the stat seems to not be calculated.

**Comment by eps1lon** [comment]
The ingame version is currently worded so that PoB cannot recognize the stat that affects intelligence. 
ingame:
> 2% increased Intelligence for each Equipped Unique Item

 vs PoB:
> 2% increased Intelligence for each Unique Item you have equipped 


If you use the version that is used by the program you should get the correct calculations. Just search for perandus signet and add the version from the program.

In general stat lines that are written with a red color are not supported yet.

**Comment by Openarl** [comment]
Fixed in the next update.
