### ISSUE TITLE
100% cold res (immune) combined with 50% flask effect Taste of Hate only reduces phys damage reduction by 18%

### ISSUE THREAD

**Issue by karlperemil** [Openarl/PathOfBuilding#841]
Should probably be 30%.
Is the x% of physical damage taken as Y damage not accounting for resists above 75%?

**Comment by Openarl** [comment]
Could you give me your build? It would make it far easier to figure this out.

**Comment by karlperemil** [comment]
https://pastebin.com/ckfb39aJ

**Comment by Openarl** [comment]
Oh... Taste of Hate doesn't affect the Physical Damage Reduction stat in the way you seem to be expecting it to.
What that number shows is an approximation of the reduction of Physical damage that you actually take _as Physical_; the only reason it goes up at all when activating Taste of Hate is that your Armour becomes more effective, since you're taking less Physical damage.
For the overall reduction on incoming Physical damage (and other damage types), you need to consult the Damage Taken section of the Calcs tab. You'll see there that in your case, the incoming Physical Hit damage multiplier goes from 0.28 to 0.13 when activating Taste of Hate, which is a relative reduction of ~54%.

**Comment by karlperemil** [comment]
Great, thanks for the explanation!
