### ISSUE TITLE
Custom chest

### ISSUE THREAD

**Issue by alazlamdurai** [Openarl/PathOfBuilding#93]
![custom chest](https://cloud.githubusercontent.com/assets/24441165/21076605/b3cb66f2-befd-11e6-959e-b41951a40d12.png)

I am trying to build a custom chest rather than use the Astral or Glorious Plate defaults.  I want a realistic view of what my gear will look like since I'm not sure I'll be able to get those 6-linked.  When trying to make a custom chest with my own implicit, the final Armour value is actually less than what I input.  Any thoughts on how to fix this?  In the picture I put in 500 but out comes 454 even though there should be no other modifiers.  Thanks!

**Comment by Openarl** [comment]
I think you're misunderstanding what an implicit is. Implicit modifiers are modifiers that are always present on a given item, regardless of rarity. The armour amount on an item isn't an implicit, or indeed a modifier at all, it's just a number that's calculated and displayed based on the item's modifiers. As such, you can't specify it directly (which is why it shows in red in the item tooltip, as the program doesn't recognise it as a modifier).

If you're creating a custom armour piece like this, in order to change the armour/evasion/ES you need to add a modifier that changes it. For example:

Armour Chest
Majestic Plate
+100 to Armour

Incidentally, lines like "Implicits:" and "Prefixes:" aren't generally necessary for the program to correctly process an item, so you can leave them out when creating a new item (so that example I gave is all that is required for that item to work).

**Comment by alazlamdurai** [comment]
Awesome thank you!  I typed in Majestic Plate and it correctly output what the Armour displayed should be (375 base Armour * 1.2 for quality or 454).  Then I just added the other modifiers and it works great.

**Comment by alazlamdurai** [comment]
Okay the above method works really well for everything except Two-Toned Boots, which has three versions but I don't know how to get the program to identify the correct one.  Any ideas?  It recognizes the Armour / ES version and I could subtract the appropriate Armour and ES, then add the right Evasion but that feels clunky and I don't know if that affects Armour totals.
