### ISSUE TITLE
Option to ignore Ascendancies on "Show Node Power"

### ISSUE THREAD

**Issue by SkPhilipp** [Openarl/PathOfBuilding#961]
This is a feature request.

It would be great if the "Show Node Power" checkbox had extra options to ignore other Ascendancies.

For example; I have a build where Berserker's Aspect of Carnage is bright yellow for 4M DPS, however as a Deadeye this is not really relevant. Because of the color scaling every other node on the skilltree which I actually can pick is almost the same color of dark red, making it hard to spot areas where I could potentially get more DPS without manually going over each cluster.

**Comment by Openarl** [comment]
This is in fact already the case; only reachable nodes (i.e excluding other ascendancies) are used when calculating the maximum power values for the colour scaling. As such, the highest power reachable nodes will always be shown as the same colour, regardless of those other nodes.
However, the colour scaling on individual nodes isn't capped at that maximum, and consequently non-reachable nodes can be shown with more intense colouring if they exceed those maximums; this is intentional, as it allows a visual assessment of other ascendancies.
For reference, here's the scaling for the default node power colour scheme (Red/Blue; this can be changed in the Options dialog). The black lines mark the boundaries of the colours used for reachable nodes (the top left region).
![power-rb](https://user-images.githubusercontent.com/19189971/38429750-ac695c80-3a02-11e8-892e-33ad7bd71813.png)
