### ISSUE TITLE
Incorrect ES/Life calculations

### ISSUE THREAD

**Issue by Zedliminal** [Openarl/PathOfBuilding#97]
I've imported my character's tree, jewels, items and skills and it is showing wrong total life and energy shield. 

Ingame life: 3566
PathOfbuilding: 3465
In-game energy shield: 1772
PathOfbuilding: 1941

**Comment by Openarl** [comment]
The account and character names would have helped, but lucky I saw your forum post. So:
1) The discrepancy in life is because you didn't set the bandit choices after importing; selecting Oak on normal accounts for it perfectly. The program cannot import the bandit choices as that information isn't available anywhere in the character API, so it relies on user input. There is actually a note in the import section regarding that, but I presume you missed it.
2) For energy shield, this is the program's fault. All imported items currently have their quality normalised to 20, which is something I thought I'd fixed a few updates ago, but it looks like the fix didn't work. Since your character's armour pieces generally don't have any quality, it results in a large discrepancy.
