### ISSUE TITLE
Wurm's Molt Leech and Tree values Leech - weird behavior

### ISSUE THREAD

**Issue by jimbobulator** [Openarl/PathOfBuilding#987]
https://pastebin.com/8Mpv9Vi7

Build is 100% cold conversion, so Wurm's Molt belt should not grant any mana or life leech, but removing belt drops the life leech rate shown in PoB.  Does the leech from the belt apply before elemental conversion?

Conversely, there does not appear to be any mana leech applied by the belt.  Only be enabling the Life and Mana Leech node in the passive tree can I see mana leech in PoB - the pop up on the calc's page for mana leech shows both sources (tree and belt), but removing belt doesn't affect it.

**Comment by Openarl** [comment]
Leech always applies after conversion, so Physical Attack Damage Leech modifiers will never apply if there isn't any such damage being dealt.

Your Life Leech rate drops when unequipping the belt because the belt has Strength, which affects your Damage dealt, and therefore your Leech rate since you aren't at the Leech cap.

**Comment by jimbobulator** [comment]
Ah yes, you are right, of course.  Sorry!  

Thanks for the quick response.  Cheers, and great program :).
